// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: cosmos/base/abci/v1beta1/abci.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

#import "tendermint/abci/Types.pbobjc.h"
#import "tendermint/types/Block.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ABCIMessageLog;
@class Attribute;
@class GasInfo;
@class MsgData;
@class Result;
@class StringEvent;
@class TxResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AbciRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AbciRoot : GPBRootObject
@end

#pragma mark - TxResponse

typedef GPB_ENUM(TxResponse_FieldNumber) {
  TxResponse_FieldNumber_Height = 1,
  TxResponse_FieldNumber_Txhash = 2,
  TxResponse_FieldNumber_Codespace = 3,
  TxResponse_FieldNumber_Code = 4,
  TxResponse_FieldNumber_Data_p = 5,
  TxResponse_FieldNumber_RawLog = 6,
  TxResponse_FieldNumber_LogsArray = 7,
  TxResponse_FieldNumber_Info = 8,
  TxResponse_FieldNumber_GasWanted = 9,
  TxResponse_FieldNumber_GasUsed = 10,
  TxResponse_FieldNumber_Tx = 11,
  TxResponse_FieldNumber_Timestamp = 12,
  TxResponse_FieldNumber_EventsArray = 13,
};

/**
 * TxResponse defines a structure containing relevant tx data and metadata. The
 * tags are stringified and the log is JSON decoded.
 **/
GPB_FINAL @interface TxResponse : GPBMessage

/** The block height */
@property(nonatomic, readwrite) int64_t height;

/** The transaction hash. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *txhash;

/** Namespace for the Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *codespace;

/** Response code. */
@property(nonatomic, readwrite) uint32_t code;

/** Result bytes, if any. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

/**
 * The output of the application's logger (raw string). May be
 * non-deterministic.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *rawLog;

/** The output of the application's logger (typed). May be non-deterministic. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ABCIMessageLog*> *logsArray;
/** The number of items in @c logsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger logsArray_Count;

/** Additional information. May be non-deterministic. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *info;

/** Amount of gas requested for transaction. */
@property(nonatomic, readwrite) int64_t gasWanted;

/** Amount of gas consumed by transaction. */
@property(nonatomic, readwrite) int64_t gasUsed;

/** The request transaction bytes. */
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *tx;
/** Test to see if @c tx has been set. */
@property(nonatomic, readwrite) BOOL hasTx;

/**
 * Time of the previous block. For heights > 1, it's the weighted median of
 * the timestamps of the valid votes in the block.LastCommit. For height == 1,
 * it's genesis time.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;

/**
 * Events defines all the events emitted by processing a transaction. Note,
 * these events include those emitted by processing all the messages and those
 * emitted from the ante. Whereas Logs contains the events, with
 * additional metadata, emitted only by processing the messages.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Event*> *eventsArray;
/** The number of items in @c eventsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger eventsArray_Count;

@end

#pragma mark - ABCIMessageLog

typedef GPB_ENUM(ABCIMessageLog_FieldNumber) {
  ABCIMessageLog_FieldNumber_MsgIndex = 1,
  ABCIMessageLog_FieldNumber_Log = 2,
  ABCIMessageLog_FieldNumber_EventsArray = 3,
};

/**
 * ABCIMessageLog defines a structure containing an indexed tx ABCI message log.
 **/
GPB_FINAL @interface ABCIMessageLog : GPBMessage

@property(nonatomic, readwrite) uint32_t msgIndex;

@property(nonatomic, readwrite, copy, null_resettable) NSString *log;

/**
 * Events contains a slice of Event objects that were emitted during some
 * execution.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<StringEvent*> *eventsArray;
/** The number of items in @c eventsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger eventsArray_Count;

@end

#pragma mark - StringEvent

typedef GPB_ENUM(StringEvent_FieldNumber) {
  StringEvent_FieldNumber_Type = 1,
  StringEvent_FieldNumber_AttributesArray = 2,
};

/**
 * StringEvent defines en Event object wrapper where all the attributes
 * contain key/value pairs that are strings instead of raw bytes.
 **/
GPB_FINAL @interface StringEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Attribute*> *attributesArray;
/** The number of items in @c attributesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger attributesArray_Count;

@end

#pragma mark - Attribute

typedef GPB_ENUM(Attribute_FieldNumber) {
  Attribute_FieldNumber_Key = 1,
  Attribute_FieldNumber_Value = 2,
};

/**
 * Attribute defines an attribute wrapper where the key and value are
 * strings instead of raw bytes.
 **/
GPB_FINAL @interface Attribute : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - GasInfo

typedef GPB_ENUM(GasInfo_FieldNumber) {
  GasInfo_FieldNumber_GasWanted = 1,
  GasInfo_FieldNumber_GasUsed = 2,
};

/**
 * GasInfo defines tx execution gas context.
 **/
GPB_FINAL @interface GasInfo : GPBMessage

/** GasWanted is the maximum units of work we allow this tx to perform. */
@property(nonatomic, readwrite) uint64_t gasWanted;

/** GasUsed is the amount of gas actually consumed. */
@property(nonatomic, readwrite) uint64_t gasUsed;

@end

#pragma mark - Result

typedef GPB_ENUM(Result_FieldNumber) {
  Result_FieldNumber_Data_p = 1,
  Result_FieldNumber_Log = 2,
  Result_FieldNumber_EventsArray = 3,
  Result_FieldNumber_MsgResponsesArray = 4,
};

/**
 * Result is the union of ResponseFormat and ResponseCheckTx.
 **/
GPB_FINAL @interface Result : GPBMessage

/**
 * Data is any data returned from message or handler execution. It MUST be
 * length prefixed in order to separate data from multiple message executions.
 * Deprecated. This field is still populated, but prefer msg_response instead
 * because it also contains the Msg response typeURL.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p GPB_DEPRECATED_MSG("cosmos.base.abci.v1beta1.Result.data is deprecated (see cosmos/base/abci/v1beta1/abci.proto).");

/** Log contains the log information from message or handler execution. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *log;

/**
 * Events contains a slice of Event objects that were emitted during message
 * or handler execution.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Event*> *eventsArray;
/** The number of items in @c eventsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger eventsArray_Count;

/** msg_responses contains the Msg handler responses type packed in Anys. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *msgResponsesArray;
/** The number of items in @c msgResponsesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger msgResponsesArray_Count;

@end

#pragma mark - SimulationResponse

typedef GPB_ENUM(SimulationResponse_FieldNumber) {
  SimulationResponse_FieldNumber_GasInfo = 1,
  SimulationResponse_FieldNumber_Result = 2,
};

/**
 * SimulationResponse defines the response generated when a transaction is
 * successfully simulated.
 **/
GPB_FINAL @interface SimulationResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GasInfo *gasInfo;
/** Test to see if @c gasInfo has been set. */
@property(nonatomic, readwrite) BOOL hasGasInfo;

@property(nonatomic, readwrite, strong, null_resettable) Result *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@end

#pragma mark - MsgData

typedef GPB_ENUM(MsgData_FieldNumber) {
  MsgData_FieldNumber_MsgType = 1,
  MsgData_FieldNumber_Data_p = 2,
};

/**
 * MsgData defines the data returned in a Result object during message
 * execution.
 **/
GPB_DEPRECATED_MSG("cosmos.base.abci.v1beta1.MsgData is deprecated (see cosmos/base/abci/v1beta1/abci.proto).")
GPB_FINAL @interface MsgData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - TxMsgData

typedef GPB_ENUM(TxMsgData_FieldNumber) {
  TxMsgData_FieldNumber_DataArray = 1,
  TxMsgData_FieldNumber_MsgResponsesArray = 2,
};

/**
 * TxMsgData defines a list of MsgData. A transaction will have a MsgData object
 * for each message.
 **/
GPB_FINAL @interface TxMsgData : GPBMessage

/** data field is deprecated and not populated. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MsgData*> *dataArray GPB_DEPRECATED_MSG("cosmos.base.abci.v1beta1.TxMsgData.data is deprecated (see cosmos/base/abci/v1beta1/abci.proto).");
/** The number of items in @c dataArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dataArray_Count GPB_DEPRECATED_MSG("cosmos.base.abci.v1beta1.TxMsgData.data is deprecated (see cosmos/base/abci/v1beta1/abci.proto).");

/** msg_responses contains the Msg handler responses packed into Anys. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *msgResponsesArray;
/** The number of items in @c msgResponsesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger msgResponsesArray_Count;

@end

#pragma mark - SearchTxsResult

typedef GPB_ENUM(SearchTxsResult_FieldNumber) {
  SearchTxsResult_FieldNumber_TotalCount = 1,
  SearchTxsResult_FieldNumber_Count = 2,
  SearchTxsResult_FieldNumber_PageNumber = 3,
  SearchTxsResult_FieldNumber_PageTotal = 4,
  SearchTxsResult_FieldNumber_Limit = 5,
  SearchTxsResult_FieldNumber_TxsArray = 6,
};

/**
 * SearchTxsResult defines a structure for querying txs pageable
 **/
GPB_FINAL @interface SearchTxsResult : GPBMessage

/** Count of all txs */
@property(nonatomic, readwrite) uint64_t totalCount;

/** Count of txs in current page */
@property(nonatomic, readwrite) uint64_t count;

/** Index of current page, start from 1 */
@property(nonatomic, readwrite) uint64_t pageNumber;

/** Count of total pages */
@property(nonatomic, readwrite) uint64_t pageTotal;

/** Max count txs per page */
@property(nonatomic, readwrite) uint64_t limit;

/** List of txs in current page */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TxResponse*> *txsArray;
/** The number of items in @c txsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger txsArray_Count;

@end

#pragma mark - SearchBlocksResult

typedef GPB_ENUM(SearchBlocksResult_FieldNumber) {
  SearchBlocksResult_FieldNumber_TotalCount = 1,
  SearchBlocksResult_FieldNumber_Count = 2,
  SearchBlocksResult_FieldNumber_PageNumber = 3,
  SearchBlocksResult_FieldNumber_PageTotal = 4,
  SearchBlocksResult_FieldNumber_Limit = 5,
  SearchBlocksResult_FieldNumber_BlocksArray = 6,
};

/**
 * SearchBlocksResult defines a structure for querying blocks pageable
 **/
GPB_FINAL @interface SearchBlocksResult : GPBMessage

/** Count of all blocks */
@property(nonatomic, readwrite) int64_t totalCount;

/** Count of blocks in current page */
@property(nonatomic, readwrite) int64_t count;

/** Index of current page, start from 1 */
@property(nonatomic, readwrite) int64_t pageNumber;

/** Count of total pages */
@property(nonatomic, readwrite) int64_t pageTotal;

/** Max count blocks per page */
@property(nonatomic, readwrite) int64_t limit;

/** List of blocks in current page */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Block*> *blocksArray;
/** The number of items in @c blocksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger blocksArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
