// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: cosmos/slashing/v1beta1/query.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

#import "cosmos/base/query/v1beta1/Pagination.pbobjc.h"
#import "cosmos/slashing/v1beta1/Slashing.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QueryRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface QueryRoot : GPBRootObject
@end

#pragma mark - QueryParamsRequest

/**
 * QueryParamsRequest is the request type for the Query/Params RPC method
 **/
GPB_FINAL @interface QueryParamsRequest : GPBMessage

@end

#pragma mark - QueryParamsResponse

typedef GPB_ENUM(QueryParamsResponse_FieldNumber) {
  QueryParamsResponse_FieldNumber_Params = 1,
};

/**
 * QueryParamsResponse is the response type for the Query/Params RPC method
 **/
GPB_FINAL @interface QueryParamsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Params *params;
/** Test to see if @c params has been set. */
@property(nonatomic, readwrite) BOOL hasParams;

@end

#pragma mark - QuerySigningInfoRequest

typedef GPB_ENUM(QuerySigningInfoRequest_FieldNumber) {
  QuerySigningInfoRequest_FieldNumber_ConsAddress = 1,
};

/**
 * QuerySigningInfoRequest is the request type for the Query/SigningInfo RPC
 * method
 **/
GPB_FINAL @interface QuerySigningInfoRequest : GPBMessage

/** cons_address is the address to query signing info of */
@property(nonatomic, readwrite, copy, null_resettable) NSString *consAddress;

@end

#pragma mark - QuerySigningInfoResponse

typedef GPB_ENUM(QuerySigningInfoResponse_FieldNumber) {
  QuerySigningInfoResponse_FieldNumber_ValSigningInfo = 1,
};

/**
 * QuerySigningInfoResponse is the response type for the Query/SigningInfo RPC
 * method
 **/
GPB_FINAL @interface QuerySigningInfoResponse : GPBMessage

/** val_signing_info is the signing info of requested val cons address */
@property(nonatomic, readwrite, strong, null_resettable) ValidatorSigningInfo *valSigningInfo;
/** Test to see if @c valSigningInfo has been set. */
@property(nonatomic, readwrite) BOOL hasValSigningInfo;

@end

#pragma mark - QuerySigningInfosRequest

typedef GPB_ENUM(QuerySigningInfosRequest_FieldNumber) {
  QuerySigningInfosRequest_FieldNumber_Pagination = 1,
};

/**
 * QuerySigningInfosRequest is the request type for the Query/SigningInfos RPC
 * method
 **/
GPB_FINAL @interface QuerySigningInfosRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PageRequest *pagination;
/** Test to see if @c pagination has been set. */
@property(nonatomic, readwrite) BOOL hasPagination;

@end

#pragma mark - QuerySigningInfosResponse

typedef GPB_ENUM(QuerySigningInfosResponse_FieldNumber) {
  QuerySigningInfosResponse_FieldNumber_InfoArray = 1,
  QuerySigningInfosResponse_FieldNumber_Pagination = 2,
};

/**
 * QuerySigningInfosResponse is the response type for the Query/SigningInfos RPC
 * method
 **/
GPB_FINAL @interface QuerySigningInfosResponse : GPBMessage

/** info is the signing info of all validators */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ValidatorSigningInfo*> *infoArray;
/** The number of items in @c infoArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger infoArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) PageResponse *pagination;
/** Test to see if @c pagination has been set. */
@property(nonatomic, readwrite) BOOL hasPagination;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
