/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: osmosis/tokenfactory/v1beta1/params.proto */

#ifndef PROTOBUF_C_osmosis_2ftokenfactory_2fv1beta1_2fparams_2eproto__INCLUDED
#define PROTOBUF_C_osmosis_2ftokenfactory_2fv1beta1_2fparams_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "gogoproto/gogo.pb-c.h"
#include "osmosis/tokenfactory/v1beta1/authorityMetadata.pb-c.h"
#include "cosmos_proto/cosmos.pb-c.h"
#include "cosmos/base/v1beta1/coin.pb-c.h"

typedef struct Osmosis__Tokenfactory__V1beta1__Params Osmosis__Tokenfactory__V1beta1__Params;


/* --- enums --- */


/* --- messages --- */

/*
 * Params defines the parameters for the tokenfactory module.
 */
struct  Osmosis__Tokenfactory__V1beta1__Params
{
  ProtobufCMessage base;
  size_t n_denom_creation_fee;
  Cosmos__Base__V1beta1__Coin **denom_creation_fee;
  /*
   * if denom_creation_fee is an empty array, then this field is used to add more gas consumption
   * to the base cost.
   * https://github.com/CosmWasm/token-factory/issues/11
   */
  uint64_t denom_creation_gas_consume;
};
#define OSMOSIS__TOKENFACTORY__V1BETA1__PARAMS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&osmosis__tokenfactory__v1beta1__params__descriptor) \
, 0,NULL, 0 }


/* Osmosis__Tokenfactory__V1beta1__Params methods */
void   osmosis__tokenfactory__v1beta1__params__init
                     (Osmosis__Tokenfactory__V1beta1__Params         *message);
size_t osmosis__tokenfactory__v1beta1__params__get_packed_size
                     (const Osmosis__Tokenfactory__V1beta1__Params   *message);
size_t osmosis__tokenfactory__v1beta1__params__pack
                     (const Osmosis__Tokenfactory__V1beta1__Params   *message,
                      uint8_t             *out);
size_t osmosis__tokenfactory__v1beta1__params__pack_to_buffer
                     (const Osmosis__Tokenfactory__V1beta1__Params   *message,
                      ProtobufCBuffer     *buffer);
Osmosis__Tokenfactory__V1beta1__Params *
       osmosis__tokenfactory__v1beta1__params__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   osmosis__tokenfactory__v1beta1__params__free_unpacked
                     (Osmosis__Tokenfactory__V1beta1__Params *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Osmosis__Tokenfactory__V1beta1__Params_Closure)
                 (const Osmosis__Tokenfactory__V1beta1__Params *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor osmosis__tokenfactory__v1beta1__params__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_osmosis_2ftokenfactory_2fv1beta1_2fparams_2eproto__INCLUDED */
