// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: xion/jwk/v1/tx.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package xion.jwk.v1;

@kotlin.jvm.JvmName("-initializemsgCreateAudience")
public inline fun msgCreateAudience(block: xion.jwk.v1.MsgCreateAudienceKt.Dsl.() -> kotlin.Unit): xion.jwk.v1.Tx.MsgCreateAudience =
  xion.jwk.v1.MsgCreateAudienceKt.Dsl._create(xion.jwk.v1.Tx.MsgCreateAudience.newBuilder()).apply { block() }._build()
/**
 * ```
 * MsgCreateAudience defines the message for creating an audience
 * ```
 *
 * Protobuf type `xion.jwk.v1.MsgCreateAudience`
 */
public object MsgCreateAudienceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: xion.jwk.v1.Tx.MsgCreateAudience.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: xion.jwk.v1.Tx.MsgCreateAudience.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): xion.jwk.v1.Tx.MsgCreateAudience = _builder.build()

    /**
     * ```
     * The admin address creating the audience
     * ```
     *
     * `string admin = 1 [json_name = "admin"];`
     */
    public var admin: kotlin.String
      @JvmName("getAdmin")
      get() = _builder.getAdmin()
      @JvmName("setAdmin")
      set(value) {
        _builder.setAdmin(value)
      }
    /**
     * ```
     * The admin address creating the audience
     * ```
     *
     * `string admin = 1 [json_name = "admin"];`
     */
    public fun clearAdmin() {
      _builder.clearAdmin()
    }

    /**
     * ```
     * The audience identifier
     * ```
     *
     * `string aud = 2 [json_name = "aud"];`
     */
    public var aud: kotlin.String
      @JvmName("getAud")
      get() = _builder.getAud()
      @JvmName("setAud")
      set(value) {
        _builder.setAud(value)
      }
    /**
     * ```
     * The audience identifier
     * ```
     *
     * `string aud = 2 [json_name = "aud"];`
     */
    public fun clearAud() {
      _builder.clearAud()
    }

    /**
     * ```
     * The public key for this audience
     * ```
     *
     * `string key = 3 [json_name = "key"];`
     */
    public var key: kotlin.String
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * ```
     * The public key for this audience
     * ```
     *
     * `string key = 3 [json_name = "key"];`
     */
    public fun clearKey() {
      _builder.clearKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun xion.jwk.v1.Tx.MsgCreateAudience.copy(block: xion.jwk.v1.MsgCreateAudienceKt.Dsl.() -> kotlin.Unit): xion.jwk.v1.Tx.MsgCreateAudience =
  xion.jwk.v1.MsgCreateAudienceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

