/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cosmos/epochs/v1beta1/genesis.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cosmos/epochs/v1beta1/genesis.pb-c.h"
void   cosmos__epochs__v1beta1__epoch_info__init
                     (Cosmos__Epochs__V1beta1__EpochInfo         *message)
{
  static const Cosmos__Epochs__V1beta1__EpochInfo init_value = COSMOS__EPOCHS__V1BETA1__EPOCH_INFO__INIT;
  *message = init_value;
}
size_t cosmos__epochs__v1beta1__epoch_info__get_packed_size
                     (const Cosmos__Epochs__V1beta1__EpochInfo *message)
{
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__epoch_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cosmos__epochs__v1beta1__epoch_info__pack
                     (const Cosmos__Epochs__V1beta1__EpochInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__epoch_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cosmos__epochs__v1beta1__epoch_info__pack_to_buffer
                     (const Cosmos__Epochs__V1beta1__EpochInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__epoch_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cosmos__Epochs__V1beta1__EpochInfo *
       cosmos__epochs__v1beta1__epoch_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cosmos__Epochs__V1beta1__EpochInfo *)
     protobuf_c_message_unpack (&cosmos__epochs__v1beta1__epoch_info__descriptor,
                                allocator, len, data);
}
void   cosmos__epochs__v1beta1__epoch_info__free_unpacked
                     (Cosmos__Epochs__V1beta1__EpochInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__epoch_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cosmos__epochs__v1beta1__genesis_state__init
                     (Cosmos__Epochs__V1beta1__GenesisState         *message)
{
  static const Cosmos__Epochs__V1beta1__GenesisState init_value = COSMOS__EPOCHS__V1BETA1__GENESIS_STATE__INIT;
  *message = init_value;
}
size_t cosmos__epochs__v1beta1__genesis_state__get_packed_size
                     (const Cosmos__Epochs__V1beta1__GenesisState *message)
{
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__genesis_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cosmos__epochs__v1beta1__genesis_state__pack
                     (const Cosmos__Epochs__V1beta1__GenesisState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__genesis_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cosmos__epochs__v1beta1__genesis_state__pack_to_buffer
                     (const Cosmos__Epochs__V1beta1__GenesisState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__genesis_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cosmos__Epochs__V1beta1__GenesisState *
       cosmos__epochs__v1beta1__genesis_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cosmos__Epochs__V1beta1__GenesisState *)
     protobuf_c_message_unpack (&cosmos__epochs__v1beta1__genesis_state__descriptor,
                                allocator, len, data);
}
void   cosmos__epochs__v1beta1__genesis_state__free_unpacked
                     (Cosmos__Epochs__V1beta1__GenesisState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cosmos__epochs__v1beta1__genesis_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cosmos__epochs__v1beta1__epoch_info__field_descriptors[7] =
{
  {
    "identifier",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Epochs__V1beta1__EpochInfo, identifier),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Epochs__V1beta1__EpochInfo, start_time),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Epochs__V1beta1__EpochInfo, duration),
    &google__protobuf__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_epoch",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Epochs__V1beta1__EpochInfo, current_epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_epoch_start_time",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Epochs__V1beta1__EpochInfo, current_epoch_start_time),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epoch_counting_started",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Epochs__V1beta1__EpochInfo, epoch_counting_started),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_epoch_start_height",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Epochs__V1beta1__EpochInfo, current_epoch_start_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cosmos__epochs__v1beta1__epoch_info__field_indices_by_name[] = {
  3,   /* field[3] = current_epoch */
  6,   /* field[6] = current_epoch_start_height */
  4,   /* field[4] = current_epoch_start_time */
  2,   /* field[2] = duration */
  5,   /* field[5] = epoch_counting_started */
  0,   /* field[0] = identifier */
  1,   /* field[1] = start_time */
};
static const ProtobufCIntRange cosmos__epochs__v1beta1__epoch_info__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cosmos__epochs__v1beta1__epoch_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cosmos.epochs.v1beta1.EpochInfo",
  "EpochInfo",
  "Cosmos__Epochs__V1beta1__EpochInfo",
  "cosmos.epochs.v1beta1",
  sizeof(Cosmos__Epochs__V1beta1__EpochInfo),
  7,
  cosmos__epochs__v1beta1__epoch_info__field_descriptors,
  cosmos__epochs__v1beta1__epoch_info__field_indices_by_name,
  2,  cosmos__epochs__v1beta1__epoch_info__number_ranges,
  (ProtobufCMessageInit) cosmos__epochs__v1beta1__epoch_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cosmos__epochs__v1beta1__genesis_state__field_descriptors[1] =
{
  {
    "epochs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Cosmos__Epochs__V1beta1__GenesisState, n_epochs),
    offsetof(Cosmos__Epochs__V1beta1__GenesisState, epochs),
    &cosmos__epochs__v1beta1__epoch_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cosmos__epochs__v1beta1__genesis_state__field_indices_by_name[] = {
  0,   /* field[0] = epochs */
};
static const ProtobufCIntRange cosmos__epochs__v1beta1__genesis_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cosmos__epochs__v1beta1__genesis_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cosmos.epochs.v1beta1.GenesisState",
  "GenesisState",
  "Cosmos__Epochs__V1beta1__GenesisState",
  "cosmos.epochs.v1beta1",
  sizeof(Cosmos__Epochs__V1beta1__GenesisState),
  1,
  cosmos__epochs__v1beta1__genesis_state__field_descriptors,
  cosmos__epochs__v1beta1__genesis_state__field_indices_by_name,
  1,  cosmos__epochs__v1beta1__genesis_state__number_ranges,
  (ProtobufCMessageInit) cosmos__epochs__v1beta1__genesis_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
