<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/feegrant/module/v1/module.proto

namespace Cosmos\Feegrant\Module\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Module is the config object of the feegrant module.
 *
 * Generated from protobuf message <code>cosmos.feegrant.module.v1.Module</code>
 */
class Module extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cosmos\Feegrant\Module\V1\Module::initOnce();
        parent::__construct($data);
    }

}

