// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: cosmwasm/wasm/v1/types.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AbsoluteTxPosition;
@class AccessConfig;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum AccessType

/** AccessType permission types */
typedef GPB_ENUM(AccessType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AccessType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** AccessTypeUnspecified placeholder for empty value */
  AccessType_AccessTypeUnspecified = 0,

  /** AccessTypeNobody forbidden */
  AccessType_AccessTypeNobody = 1,

  /** AccessTypeEverybody unrestricted */
  AccessType_AccessTypeEverybody = 3,

  /** AccessTypeAnyOfAddresses allow any of the addresses */
  AccessType_AccessTypeAnyOfAddresses = 4,
};

GPBEnumDescriptor *AccessType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AccessType_IsValidValue(int32_t value);

#pragma mark - Enum ContractCodeHistoryOperationType

/** ContractCodeHistoryOperationType actions that caused a code change */
typedef GPB_ENUM(ContractCodeHistoryOperationType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ContractCodeHistoryOperationType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** ContractCodeHistoryOperationTypeUnspecified placeholder for empty value */
  ContractCodeHistoryOperationType_ContractCodeHistoryOperationTypeUnspecified = 0,

  /** ContractCodeHistoryOperationTypeInit on chain contract instantiation */
  ContractCodeHistoryOperationType_ContractCodeHistoryOperationTypeInit = 1,

  /** ContractCodeHistoryOperationTypeMigrate code migration */
  ContractCodeHistoryOperationType_ContractCodeHistoryOperationTypeMigrate = 2,

  /** ContractCodeHistoryOperationTypeGenesis based on genesis data */
  ContractCodeHistoryOperationType_ContractCodeHistoryOperationTypeGenesis = 3,
};

GPBEnumDescriptor *ContractCodeHistoryOperationType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ContractCodeHistoryOperationType_IsValidValue(int32_t value);

#pragma mark - TypesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface TypesRoot : GPBRootObject
@end

#pragma mark - AccessTypeParam

typedef GPB_ENUM(AccessTypeParam_FieldNumber) {
  AccessTypeParam_FieldNumber_Value = 1,
};

/**
 * AccessTypeParam
 **/
GPB_FINAL @interface AccessTypeParam : GPBMessage

@property(nonatomic, readwrite) AccessType value;

@end

/**
 * Fetches the raw value of a @c AccessTypeParam's @c value property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AccessTypeParam_Value_RawValue(AccessTypeParam *message);
/**
 * Sets the raw value of an @c AccessTypeParam's @c value property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAccessTypeParam_Value_RawValue(AccessTypeParam *message, int32_t value);

#pragma mark - AccessConfig

typedef GPB_ENUM(AccessConfig_FieldNumber) {
  AccessConfig_FieldNumber_Permission = 1,
  AccessConfig_FieldNumber_AddressesArray = 3,
};

/**
 * AccessConfig access control type.
 **/
GPB_FINAL @interface AccessConfig : GPBMessage

@property(nonatomic, readwrite) AccessType permission;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *addressesArray;
/** The number of items in @c addressesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressesArray_Count;

@end

/**
 * Fetches the raw value of a @c AccessConfig's @c permission property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AccessConfig_Permission_RawValue(AccessConfig *message);
/**
 * Sets the raw value of an @c AccessConfig's @c permission property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAccessConfig_Permission_RawValue(AccessConfig *message, int32_t value);

#pragma mark - Params

typedef GPB_ENUM(Params_FieldNumber) {
  Params_FieldNumber_CodeUploadAccess = 1,
  Params_FieldNumber_InstantiateDefaultPermission = 2,
};

/**
 * Params defines the set of wasm parameters.
 **/
GPB_FINAL @interface Params : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AccessConfig *codeUploadAccess;
/** Test to see if @c codeUploadAccess has been set. */
@property(nonatomic, readwrite) BOOL hasCodeUploadAccess;

@property(nonatomic, readwrite) AccessType instantiateDefaultPermission;

@end

/**
 * Fetches the raw value of a @c Params's @c instantiateDefaultPermission property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Params_InstantiateDefaultPermission_RawValue(Params *message);
/**
 * Sets the raw value of an @c Params's @c instantiateDefaultPermission property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetParams_InstantiateDefaultPermission_RawValue(Params *message, int32_t value);

#pragma mark - CodeInfo

typedef GPB_ENUM(CodeInfo_FieldNumber) {
  CodeInfo_FieldNumber_CodeHash = 1,
  CodeInfo_FieldNumber_Creator = 2,
  CodeInfo_FieldNumber_InstantiateConfig = 5,
};

/**
 * CodeInfo is data for the uploaded contract WASM code
 **/
GPB_FINAL @interface CodeInfo : GPBMessage

/** CodeHash is the unique identifier created by wasmvm */
@property(nonatomic, readwrite, copy, null_resettable) NSData *codeHash;

/** Creator address who initially stored the code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *creator;

/** InstantiateConfig access control to apply on contract creation, optional */
@property(nonatomic, readwrite, strong, null_resettable) AccessConfig *instantiateConfig;
/** Test to see if @c instantiateConfig has been set. */
@property(nonatomic, readwrite) BOOL hasInstantiateConfig;

@end

#pragma mark - ContractInfo

typedef GPB_ENUM(ContractInfo_FieldNumber) {
  ContractInfo_FieldNumber_CodeId = 1,
  ContractInfo_FieldNumber_Creator = 2,
  ContractInfo_FieldNumber_Admin = 3,
  ContractInfo_FieldNumber_Label = 4,
  ContractInfo_FieldNumber_Created = 5,
  ContractInfo_FieldNumber_IbcPortId = 6,
  ContractInfo_FieldNumber_Ibc2PortId = 7,
  ContractInfo_FieldNumber_Extension = 8,
};

/**
 * ContractInfo stores a WASM contract instance
 **/
GPB_FINAL @interface ContractInfo : GPBMessage

/** CodeID is the reference to the stored Wasm code */
@property(nonatomic, readwrite) uint64_t codeId;

/** Creator address who initially instantiated the contract */
@property(nonatomic, readwrite, copy, null_resettable) NSString *creator;

/** Admin is an optional address that can execute migrations */
@property(nonatomic, readwrite, copy, null_resettable) NSString *admin;

/** Label is optional metadata to be stored with a contract instance. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

/** Created Tx position when the contract was instantiated. */
@property(nonatomic, readwrite, strong, null_resettable) AbsoluteTxPosition *created;
/** Test to see if @c created has been set. */
@property(nonatomic, readwrite) BOOL hasCreated;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ibcPortId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ibc2PortId;

/**
 * Extension is an extension point to store custom metadata within the
 * persistence model.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *extension;
/** Test to see if @c extension has been set. */
@property(nonatomic, readwrite) BOOL hasExtension;

@end

#pragma mark - ContractCodeHistoryEntry

typedef GPB_ENUM(ContractCodeHistoryEntry_FieldNumber) {
  ContractCodeHistoryEntry_FieldNumber_Operation = 1,
  ContractCodeHistoryEntry_FieldNumber_CodeId = 2,
  ContractCodeHistoryEntry_FieldNumber_Updated = 3,
  ContractCodeHistoryEntry_FieldNumber_Msg = 4,
};

/**
 * ContractCodeHistoryEntry metadata to a contract.
 **/
GPB_FINAL @interface ContractCodeHistoryEntry : GPBMessage

@property(nonatomic, readwrite) ContractCodeHistoryOperationType operation;

/** CodeID is the reference to the stored WASM code */
@property(nonatomic, readwrite) uint64_t codeId;

/** Updated Tx position when the operation was executed. */
@property(nonatomic, readwrite, strong, null_resettable) AbsoluteTxPosition *updated;
/** Test to see if @c updated has been set. */
@property(nonatomic, readwrite) BOOL hasUpdated;

@property(nonatomic, readwrite, copy, null_resettable) NSData *msg;

@end

/**
 * Fetches the raw value of a @c ContractCodeHistoryEntry's @c operation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ContractCodeHistoryEntry_Operation_RawValue(ContractCodeHistoryEntry *message);
/**
 * Sets the raw value of an @c ContractCodeHistoryEntry's @c operation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetContractCodeHistoryEntry_Operation_RawValue(ContractCodeHistoryEntry *message, int32_t value);

#pragma mark - AbsoluteTxPosition

typedef GPB_ENUM(AbsoluteTxPosition_FieldNumber) {
  AbsoluteTxPosition_FieldNumber_BlockHeight = 1,
  AbsoluteTxPosition_FieldNumber_TxIndex = 2,
};

/**
 * AbsoluteTxPosition is a unique transaction position that allows for global
 * ordering of transactions.
 **/
GPB_FINAL @interface AbsoluteTxPosition : GPBMessage

/** BlockHeight is the block the contract was created at */
@property(nonatomic, readwrite) uint64_t blockHeight;

/**
 * TxIndex is a monotonic counter within the block (actual transaction index,
 * or gas consumed)
 **/
@property(nonatomic, readwrite) uint64_t txIndex;

@end

#pragma mark - Model

typedef GPB_ENUM(Model_FieldNumber) {
  Model_FieldNumber_Key = 1,
  Model_FieldNumber_Value = 2,
};

/**
 * Model is a struct that holds a KV pair
 **/
GPB_FINAL @interface Model : GPBMessage

/** hex-encode key to read it better (this is often ascii) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *key;

/** base64-encode raw value */
@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
