/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ibc/applications/packet_forward_middleware/v1/genesis.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ibc/applications/packet_forward_middleware/v1/genesis.pb-c.h"
void   ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__init
                     (Ibc__Applications__PacketForwardMiddleware__V1__GenesisState__InFlightPacketsEntry         *message)
{
  static const Ibc__Applications__PacketForwardMiddleware__V1__GenesisState__InFlightPacketsEntry init_value = IBC__APPLICATIONS__PACKET_FORWARD_MIDDLEWARE__V1__GENESIS_STATE__IN_FLIGHT_PACKETS_ENTRY__INIT;
  *message = init_value;
}
void   ibc__applications__packet_forward_middleware__v1__genesis_state__init
                     (Ibc__Applications__PacketForwardMiddleware__V1__GenesisState         *message)
{
  static const Ibc__Applications__PacketForwardMiddleware__V1__GenesisState init_value = IBC__APPLICATIONS__PACKET_FORWARD_MIDDLEWARE__V1__GENESIS_STATE__INIT;
  *message = init_value;
}
size_t ibc__applications__packet_forward_middleware__v1__genesis_state__get_packed_size
                     (const Ibc__Applications__PacketForwardMiddleware__V1__GenesisState *message)
{
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__genesis_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ibc__applications__packet_forward_middleware__v1__genesis_state__pack
                     (const Ibc__Applications__PacketForwardMiddleware__V1__GenesisState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__genesis_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ibc__applications__packet_forward_middleware__v1__genesis_state__pack_to_buffer
                     (const Ibc__Applications__PacketForwardMiddleware__V1__GenesisState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__genesis_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ibc__Applications__PacketForwardMiddleware__V1__GenesisState *
       ibc__applications__packet_forward_middleware__v1__genesis_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ibc__Applications__PacketForwardMiddleware__V1__GenesisState *)
     protobuf_c_message_unpack (&ibc__applications__packet_forward_middleware__v1__genesis_state__descriptor,
                                allocator, len, data);
}
void   ibc__applications__packet_forward_middleware__v1__genesis_state__free_unpacked
                     (Ibc__Applications__PacketForwardMiddleware__V1__GenesisState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__genesis_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ibc__applications__packet_forward_middleware__v1__in_flight_packet__init
                     (Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket         *message)
{
  static const Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket init_value = IBC__APPLICATIONS__PACKET_FORWARD_MIDDLEWARE__V1__IN_FLIGHT_PACKET__INIT;
  *message = init_value;
}
size_t ibc__applications__packet_forward_middleware__v1__in_flight_packet__get_packed_size
                     (const Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket *message)
{
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__in_flight_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ibc__applications__packet_forward_middleware__v1__in_flight_packet__pack
                     (const Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__in_flight_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ibc__applications__packet_forward_middleware__v1__in_flight_packet__pack_to_buffer
                     (const Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__in_flight_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket *
       ibc__applications__packet_forward_middleware__v1__in_flight_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket *)
     protobuf_c_message_unpack (&ibc__applications__packet_forward_middleware__v1__in_flight_packet__descriptor,
                                allocator, len, data);
}
void   ibc__applications__packet_forward_middleware__v1__in_flight_packet__free_unpacked
                     (Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ibc__applications__packet_forward_middleware__v1__in_flight_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__GenesisState__InFlightPacketsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__GenesisState__InFlightPacketsEntry, value),
    &ibc__applications__packet_forward_middleware__v1__in_flight_packet__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ibc.applications.packet_forward_middleware.v1.GenesisState.InFlightPacketsEntry",
  "InFlightPacketsEntry",
  "Ibc__Applications__PacketForwardMiddleware__V1__GenesisState__InFlightPacketsEntry",
  "ibc.applications.packet_forward_middleware.v1",
  sizeof(Ibc__Applications__PacketForwardMiddleware__V1__GenesisState__InFlightPacketsEntry),
  2,
  ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__field_descriptors,
  ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__field_indices_by_name,
  1,  ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__number_ranges,
  (ProtobufCMessageInit) ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ibc__applications__packet_forward_middleware__v1__genesis_state__field_descriptors[1] =
{
  {
    "in_flight_packets",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__GenesisState, n_in_flight_packets),
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__GenesisState, in_flight_packets),
    &ibc__applications__packet_forward_middleware__v1__genesis_state__in_flight_packets_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ibc__applications__packet_forward_middleware__v1__genesis_state__field_indices_by_name[] = {
  0,   /* field[0] = in_flight_packets */
};
static const ProtobufCIntRange ibc__applications__packet_forward_middleware__v1__genesis_state__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ibc__applications__packet_forward_middleware__v1__genesis_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ibc.applications.packet_forward_middleware.v1.GenesisState",
  "GenesisState",
  "Ibc__Applications__PacketForwardMiddleware__V1__GenesisState",
  "ibc.applications.packet_forward_middleware.v1",
  sizeof(Ibc__Applications__PacketForwardMiddleware__V1__GenesisState),
  1,
  ibc__applications__packet_forward_middleware__v1__genesis_state__field_descriptors,
  ibc__applications__packet_forward_middleware__v1__genesis_state__field_indices_by_name,
  1,  ibc__applications__packet_forward_middleware__v1__genesis_state__number_ranges,
  (ProtobufCMessageInit) ibc__applications__packet_forward_middleware__v1__genesis_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ibc__applications__packet_forward_middleware__v1__in_flight_packet__field_descriptors[12] =
{
  {
    "original_sender_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, original_sender_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refund_channel_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, refund_channel_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refund_port_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, refund_port_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_src_channel_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, packet_src_channel_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_src_port_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, packet_src_port_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_timeout_timestamp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, packet_timeout_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_timeout_height",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, packet_timeout_height),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_data",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, packet_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refund_sequence",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, refund_sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retries_remaining",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, retries_remaining),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonrefundable",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket, nonrefundable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ibc__applications__packet_forward_middleware__v1__in_flight_packet__field_indices_by_name[] = {
  11,   /* field[11] = nonrefundable */
  0,   /* field[0] = original_sender_address */
  7,   /* field[7] = packet_data */
  3,   /* field[3] = packet_src_channel_id */
  4,   /* field[4] = packet_src_port_id */
  6,   /* field[6] = packet_timeout_height */
  5,   /* field[5] = packet_timeout_timestamp */
  1,   /* field[1] = refund_channel_id */
  2,   /* field[2] = refund_port_id */
  8,   /* field[8] = refund_sequence */
  9,   /* field[9] = retries_remaining */
  10,   /* field[10] = timeout */
};
static const ProtobufCIntRange ibc__applications__packet_forward_middleware__v1__in_flight_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor ibc__applications__packet_forward_middleware__v1__in_flight_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ibc.applications.packet_forward_middleware.v1.InFlightPacket",
  "InFlightPacket",
  "Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket",
  "ibc.applications.packet_forward_middleware.v1",
  sizeof(Ibc__Applications__PacketForwardMiddleware__V1__InFlightPacket),
  12,
  ibc__applications__packet_forward_middleware__v1__in_flight_packet__field_descriptors,
  ibc__applications__packet_forward_middleware__v1__in_flight_packet__field_indices_by_name,
  1,  ibc__applications__packet_forward_middleware__v1__in_flight_packet__number_ranges,
  (ProtobufCMessageInit) ibc__applications__packet_forward_middleware__v1__in_flight_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
