// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xion/mint/v1/genesis.proto
// Protobuf Java Version: 4.29.4

package xion.mint.v1;

public final class Genesis {
  private Genesis() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 4,
      /* suffix= */ "",
      Genesis.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenesisStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xion.mint.v1.GenesisState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * minter is a space for holding current inflation information.
     * </pre>
     *
     * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return Whether the minter field is set.
     */
    boolean hasMinter();
    /**
     * <pre>
     * minter is a space for holding current inflation information.
     * </pre>
     *
     * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return The minter.
     */
    xion.mint.v1.Mint.Minter getMinter();
    /**
     * <pre>
     * minter is a space for holding current inflation information.
     * </pre>
     *
     * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     */
    xion.mint.v1.Mint.MinterOrBuilder getMinterOrBuilder();

    /**
     * <pre>
     * params defines all the parameters of the module.
     * </pre>
     *
     * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return Whether the params field is set.
     */
    boolean hasParams();
    /**
     * <pre>
     * params defines all the parameters of the module.
     * </pre>
     *
     * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return The params.
     */
    xion.mint.v1.Mint.Params getParams();
    /**
     * <pre>
     * params defines all the parameters of the module.
     * </pre>
     *
     * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     */
    xion.mint.v1.Mint.ParamsOrBuilder getParamsOrBuilder();
  }
  /**
   * <pre>
   * GenesisState defines the mint module's genesis state.
   * </pre>
   *
   * Protobuf type {@code xion.mint.v1.GenesisState}
   */
  public static final class GenesisState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:xion.mint.v1.GenesisState)
      GenesisStateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 4,
        /* suffix= */ "",
        GenesisState.class.getName());
    }
    // Use GenesisState.newBuilder() to construct.
    private GenesisState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GenesisState() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xion.mint.v1.Genesis.internal_static_xion_mint_v1_GenesisState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xion.mint.v1.Genesis.internal_static_xion_mint_v1_GenesisState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xion.mint.v1.Genesis.GenesisState.class, xion.mint.v1.Genesis.GenesisState.Builder.class);
    }

    private int bitField0_;
    public static final int MINTER_FIELD_NUMBER = 1;
    private xion.mint.v1.Mint.Minter minter_;
    /**
     * <pre>
     * minter is a space for holding current inflation information.
     * </pre>
     *
     * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return Whether the minter field is set.
     */
    @java.lang.Override
    public boolean hasMinter() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * minter is a space for holding current inflation information.
     * </pre>
     *
     * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return The minter.
     */
    @java.lang.Override
    public xion.mint.v1.Mint.Minter getMinter() {
      return minter_ == null ? xion.mint.v1.Mint.Minter.getDefaultInstance() : minter_;
    }
    /**
     * <pre>
     * minter is a space for holding current inflation information.
     * </pre>
     *
     * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     */
    @java.lang.Override
    public xion.mint.v1.Mint.MinterOrBuilder getMinterOrBuilder() {
      return minter_ == null ? xion.mint.v1.Mint.Minter.getDefaultInstance() : minter_;
    }

    public static final int PARAMS_FIELD_NUMBER = 2;
    private xion.mint.v1.Mint.Params params_;
    /**
     * <pre>
     * params defines all the parameters of the module.
     * </pre>
     *
     * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return Whether the params field is set.
     */
    @java.lang.Override
    public boolean hasParams() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * params defines all the parameters of the module.
     * </pre>
     *
     * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return The params.
     */
    @java.lang.Override
    public xion.mint.v1.Mint.Params getParams() {
      return params_ == null ? xion.mint.v1.Mint.Params.getDefaultInstance() : params_;
    }
    /**
     * <pre>
     * params defines all the parameters of the module.
     * </pre>
     *
     * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     */
    @java.lang.Override
    public xion.mint.v1.Mint.ParamsOrBuilder getParamsOrBuilder() {
      return params_ == null ? xion.mint.v1.Mint.Params.getDefaultInstance() : params_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMinter());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getParams());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMinter());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getParams());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xion.mint.v1.Genesis.GenesisState)) {
        return super.equals(obj);
      }
      xion.mint.v1.Genesis.GenesisState other = (xion.mint.v1.Genesis.GenesisState) obj;

      if (hasMinter() != other.hasMinter()) return false;
      if (hasMinter()) {
        if (!getMinter()
            .equals(other.getMinter())) return false;
      }
      if (hasParams() != other.hasParams()) return false;
      if (hasParams()) {
        if (!getParams()
            .equals(other.getParams())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMinter()) {
        hash = (37 * hash) + MINTER_FIELD_NUMBER;
        hash = (53 * hash) + getMinter().hashCode();
      }
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static xion.mint.v1.Genesis.GenesisState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static xion.mint.v1.Genesis.GenesisState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static xion.mint.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xion.mint.v1.Genesis.GenesisState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * GenesisState defines the mint module's genesis state.
     * </pre>
     *
     * Protobuf type {@code xion.mint.v1.GenesisState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xion.mint.v1.GenesisState)
        xion.mint.v1.Genesis.GenesisStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xion.mint.v1.Genesis.internal_static_xion_mint_v1_GenesisState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xion.mint.v1.Genesis.internal_static_xion_mint_v1_GenesisState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xion.mint.v1.Genesis.GenesisState.class, xion.mint.v1.Genesis.GenesisState.Builder.class);
      }

      // Construct using xion.mint.v1.Genesis.GenesisState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getMinterFieldBuilder();
          getParamsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        minter_ = null;
        if (minterBuilder_ != null) {
          minterBuilder_.dispose();
          minterBuilder_ = null;
        }
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xion.mint.v1.Genesis.internal_static_xion_mint_v1_GenesisState_descriptor;
      }

      @java.lang.Override
      public xion.mint.v1.Genesis.GenesisState getDefaultInstanceForType() {
        return xion.mint.v1.Genesis.GenesisState.getDefaultInstance();
      }

      @java.lang.Override
      public xion.mint.v1.Genesis.GenesisState build() {
        xion.mint.v1.Genesis.GenesisState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xion.mint.v1.Genesis.GenesisState buildPartial() {
        xion.mint.v1.Genesis.GenesisState result = new xion.mint.v1.Genesis.GenesisState(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(xion.mint.v1.Genesis.GenesisState result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.minter_ = minterBuilder_ == null
              ? minter_
              : minterBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.params_ = paramsBuilder_ == null
              ? params_
              : paramsBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xion.mint.v1.Genesis.GenesisState) {
          return mergeFrom((xion.mint.v1.Genesis.GenesisState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xion.mint.v1.Genesis.GenesisState other) {
        if (other == xion.mint.v1.Genesis.GenesisState.getDefaultInstance()) return this;
        if (other.hasMinter()) {
          mergeMinter(other.getMinter());
        }
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMinterFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getParamsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private xion.mint.v1.Mint.Minter minter_;
      private com.google.protobuf.SingleFieldBuilder<
          xion.mint.v1.Mint.Minter, xion.mint.v1.Mint.Minter.Builder, xion.mint.v1.Mint.MinterOrBuilder> minterBuilder_;
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       * @return Whether the minter field is set.
       */
      public boolean hasMinter() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       * @return The minter.
       */
      public xion.mint.v1.Mint.Minter getMinter() {
        if (minterBuilder_ == null) {
          return minter_ == null ? xion.mint.v1.Mint.Minter.getDefaultInstance() : minter_;
        } else {
          return minterBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder setMinter(xion.mint.v1.Mint.Minter value) {
        if (minterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          minter_ = value;
        } else {
          minterBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder setMinter(
          xion.mint.v1.Mint.Minter.Builder builderForValue) {
        if (minterBuilder_ == null) {
          minter_ = builderForValue.build();
        } else {
          minterBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder mergeMinter(xion.mint.v1.Mint.Minter value) {
        if (minterBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            minter_ != null &&
            minter_ != xion.mint.v1.Mint.Minter.getDefaultInstance()) {
            getMinterBuilder().mergeFrom(value);
          } else {
            minter_ = value;
          }
        } else {
          minterBuilder_.mergeFrom(value);
        }
        if (minter_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder clearMinter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        minter_ = null;
        if (minterBuilder_ != null) {
          minterBuilder_.dispose();
          minterBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public xion.mint.v1.Mint.Minter.Builder getMinterBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMinterFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public xion.mint.v1.Mint.MinterOrBuilder getMinterOrBuilder() {
        if (minterBuilder_ != null) {
          return minterBuilder_.getMessageOrBuilder();
        } else {
          return minter_ == null ?
              xion.mint.v1.Mint.Minter.getDefaultInstance() : minter_;
        }
      }
      /**
       * <pre>
       * minter is a space for holding current inflation information.
       * </pre>
       *
       * <code>.xion.mint.v1.Minter minter = 1 [json_name = "minter", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          xion.mint.v1.Mint.Minter, xion.mint.v1.Mint.Minter.Builder, xion.mint.v1.Mint.MinterOrBuilder> 
          getMinterFieldBuilder() {
        if (minterBuilder_ == null) {
          minterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              xion.mint.v1.Mint.Minter, xion.mint.v1.Mint.Minter.Builder, xion.mint.v1.Mint.MinterOrBuilder>(
                  getMinter(),
                  getParentForChildren(),
                  isClean());
          minter_ = null;
        }
        return minterBuilder_;
      }

      private xion.mint.v1.Mint.Params params_;
      private com.google.protobuf.SingleFieldBuilder<
          xion.mint.v1.Mint.Params, xion.mint.v1.Mint.Params.Builder, xion.mint.v1.Mint.ParamsOrBuilder> paramsBuilder_;
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       * @return Whether the params field is set.
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       * @return The params.
       */
      public xion.mint.v1.Mint.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? xion.mint.v1.Mint.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder setParams(xion.mint.v1.Mint.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
        } else {
          paramsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder setParams(
          xion.mint.v1.Mint.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder mergeParams(xion.mint.v1.Mint.Params value) {
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            params_ != null &&
            params_ != xion.mint.v1.Mint.Params.getDefaultInstance()) {
            getParamsBuilder().mergeFrom(value);
          } else {
            params_ = value;
          }
        } else {
          paramsBuilder_.mergeFrom(value);
        }
        if (params_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000002);
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public xion.mint.v1.Mint.Params.Builder getParamsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public xion.mint.v1.Mint.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              xion.mint.v1.Mint.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <pre>
       * params defines all the parameters of the module.
       * </pre>
       *
       * <code>.xion.mint.v1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          xion.mint.v1.Mint.Params, xion.mint.v1.Mint.Params.Builder, xion.mint.v1.Mint.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              xion.mint.v1.Mint.Params, xion.mint.v1.Mint.Params.Builder, xion.mint.v1.Mint.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:xion.mint.v1.GenesisState)
    }

    // @@protoc_insertion_point(class_scope:xion.mint.v1.GenesisState)
    private static final xion.mint.v1.Genesis.GenesisState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xion.mint.v1.Genesis.GenesisState();
    }

    public static xion.mint.v1.Genesis.GenesisState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenesisState>
        PARSER = new com.google.protobuf.AbstractParser<GenesisState>() {
      @java.lang.Override
      public GenesisState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenesisState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenesisState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xion.mint.v1.Genesis.GenesisState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xion_mint_v1_GenesisState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xion_mint_v1_GenesisState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032xion/mint/v1/genesis.proto\022\014xion.mint." +
      "v1\032\024gogoproto/gogo.proto\032\027xion/mint/v1/m" +
      "int.proto\032\021amino/amino.proto\"\200\001\n\014Genesis" +
      "State\0227\n\006minter\030\001 \001(\0132\024.xion.mint.v1.Min" +
      "terB\t\310\336\037\000\250\347\260*\001R\006minter\0227\n\006params\030\002 \001(\0132\024" +
      ".xion.mint.v1.ParamsB\t\310\336\037\000\250\347\260*\001R\006paramsB" +
      ")Z\'github.com/burnt-labs/xion/x/mint/typ" +
      "esb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          xion.mint.v1.Mint.getDescriptor(),
          amino.Amino.getDescriptor(),
        });
    internal_static_xion_mint_v1_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xion_mint_v1_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_xion_mint_v1_GenesisState_descriptor,
        new java.lang.String[] { "Minter", "Params", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.GoGoProtos.getDescriptor();
    xion.mint.v1.Mint.getDescriptor();
    amino.Amino.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(amino.Amino.dontOmitempty);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
