<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ibc/core/channel/v2/tx.proto

namespace Ibc\Core\Channel\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MsgAcknowledgement receives incoming IBC acknowledgement.
 *
 * Generated from protobuf message <code>ibc.core.channel.v2.MsgAcknowledgement</code>
 */
class MsgAcknowledgement extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ibc.core.channel.v2.Packet packet = 1 [json_name = "packet", (.gogoproto.nullable) = false];</code>
     */
    protected $packet = null;
    /**
     * Generated from protobuf field <code>.ibc.core.channel.v2.Acknowledgement acknowledgement = 2 [json_name = "acknowledgement", (.gogoproto.nullable) = false];</code>
     */
    protected $acknowledgement = null;
    /**
     * Generated from protobuf field <code>bytes proof_acked = 3 [json_name = "proofAcked"];</code>
     */
    protected $proof_acked = '';
    /**
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 4 [json_name = "proofHeight", (.gogoproto.nullable) = false];</code>
     */
    protected $proof_height = null;
    /**
     * Generated from protobuf field <code>string signer = 5 [json_name = "signer"];</code>
     */
    protected $signer = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ibc\Core\Channel\V2\Packet $packet
     *     @type \Ibc\Core\Channel\V2\Acknowledgement $acknowledgement
     *     @type string $proof_acked
     *     @type \Ibc\Core\Client\V1\Height $proof_height
     *     @type string $signer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Core\Channel\V2\Tx::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v2.Packet packet = 1 [json_name = "packet", (.gogoproto.nullable) = false];</code>
     * @return \Ibc\Core\Channel\V2\Packet|null
     */
    public function getPacket()
    {
        return $this->packet;
    }

    public function hasPacket()
    {
        return isset($this->packet);
    }

    public function clearPacket()
    {
        unset($this->packet);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v2.Packet packet = 1 [json_name = "packet", (.gogoproto.nullable) = false];</code>
     * @param \Ibc\Core\Channel\V2\Packet $var
     * @return $this
     */
    public function setPacket($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Channel\V2\Packet::class);
        $this->packet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v2.Acknowledgement acknowledgement = 2 [json_name = "acknowledgement", (.gogoproto.nullable) = false];</code>
     * @return \Ibc\Core\Channel\V2\Acknowledgement|null
     */
    public function getAcknowledgement()
    {
        return $this->acknowledgement;
    }

    public function hasAcknowledgement()
    {
        return isset($this->acknowledgement);
    }

    public function clearAcknowledgement()
    {
        unset($this->acknowledgement);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.channel.v2.Acknowledgement acknowledgement = 2 [json_name = "acknowledgement", (.gogoproto.nullable) = false];</code>
     * @param \Ibc\Core\Channel\V2\Acknowledgement $var
     * @return $this
     */
    public function setAcknowledgement($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Channel\V2\Acknowledgement::class);
        $this->acknowledgement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes proof_acked = 3 [json_name = "proofAcked"];</code>
     * @return string
     */
    public function getProofAcked()
    {
        return $this->proof_acked;
    }

    /**
     * Generated from protobuf field <code>bytes proof_acked = 3 [json_name = "proofAcked"];</code>
     * @param string $var
     * @return $this
     */
    public function setProofAcked($var)
    {
        GPBUtil::checkString($var, False);
        $this->proof_acked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 4 [json_name = "proofHeight", (.gogoproto.nullable) = false];</code>
     * @return \Ibc\Core\Client\V1\Height|null
     */
    public function getProofHeight()
    {
        return $this->proof_height;
    }

    public function hasProofHeight()
    {
        return isset($this->proof_height);
    }

    public function clearProofHeight()
    {
        unset($this->proof_height);
    }

    /**
     * Generated from protobuf field <code>.ibc.core.client.v1.Height proof_height = 4 [json_name = "proofHeight", (.gogoproto.nullable) = false];</code>
     * @param \Ibc\Core\Client\V1\Height $var
     * @return $this
     */
    public function setProofHeight($var)
    {
        GPBUtil::checkMessage($var, \Ibc\Core\Client\V1\Height::class);
        $this->proof_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signer = 5 [json_name = "signer"];</code>
     * @return string
     */
    public function getSigner()
    {
        return $this->signer;
    }

    /**
     * Generated from protobuf field <code>string signer = 5 [json_name = "signer"];</code>
     * @param string $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkString($var, True);
        $this->signer = $var;

        return $this;
    }

}

