<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ibc/core/channel/v2/query.proto

namespace Ibc\Core\Channel\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * QueryUnreceivedAcks is the request type for the
 * Query/UnreceivedAcks RPC method
 *
 * Generated from protobuf message <code>ibc.core.channel.v2.QueryUnreceivedAcksRequest</code>
 */
class QueryUnreceivedAcksRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * client unique identifier
     *
     * Generated from protobuf field <code>string client_id = 1 [json_name = "clientId"];</code>
     */
    protected $client_id = '';
    /**
     * list of acknowledgement sequences
     *
     * Generated from protobuf field <code>repeated uint64 packet_ack_sequences = 2 [json_name = "packetAckSequences"];</code>
     */
    private $packet_ack_sequences;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client_id
     *           client unique identifier
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $packet_ack_sequences
     *           list of acknowledgement sequences
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ibc\Core\Channel\V2\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * client unique identifier
     *
     * Generated from protobuf field <code>string client_id = 1 [json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * client unique identifier
     *
     * Generated from protobuf field <code>string client_id = 1 [json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * list of acknowledgement sequences
     *
     * Generated from protobuf field <code>repeated uint64 packet_ack_sequences = 2 [json_name = "packetAckSequences"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPacketAckSequences()
    {
        return $this->packet_ack_sequences;
    }

    /**
     * list of acknowledgement sequences
     *
     * Generated from protobuf field <code>repeated uint64 packet_ack_sequences = 2 [json_name = "packetAckSequences"];</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPacketAckSequences($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->packet_ack_sequences = $arr;

        return $this;
    }

}

