// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/app/v1alpha1/query.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cosmos_2fapp_2fv1alpha1_2fquery_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_cosmos_2fapp_2fv1alpha1_2fquery_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "cosmos/app/v1alpha1/config.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cosmos_2fapp_2fv1alpha1_2fquery_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cosmos_2fapp_2fv1alpha1_2fquery_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_cosmos_2fapp_2fv1alpha1_2fquery_2eproto;
namespace cosmos {
namespace app {
namespace v1alpha1 {
class QueryConfigRequest;
struct QueryConfigRequestDefaultTypeInternal;
extern QueryConfigRequestDefaultTypeInternal _QueryConfigRequest_default_instance_;
class QueryConfigResponse;
struct QueryConfigResponseDefaultTypeInternal;
extern QueryConfigResponseDefaultTypeInternal _QueryConfigResponse_default_instance_;
}  // namespace v1alpha1
}  // namespace app
}  // namespace cosmos
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cosmos {
namespace app {
namespace v1alpha1 {

// ===================================================================


// -------------------------------------------------------------------

class QueryConfigRequest final :
    public ::google::protobuf::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:cosmos.app.v1alpha1.QueryConfigRequest) */ {
 public:
  inline QueryConfigRequest() : QueryConfigRequest(nullptr) {}
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR QueryConfigRequest(::google::protobuf::internal::ConstantInitialized);

  QueryConfigRequest(const QueryConfigRequest& from);
  QueryConfigRequest(QueryConfigRequest&& from) noexcept
    : QueryConfigRequest() {
    *this = ::std::move(from);
  }

  inline QueryConfigRequest& operator=(const QueryConfigRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryConfigRequest& operator=(QueryConfigRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryConfigRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryConfigRequest* internal_default_instance() {
    return reinterpret_cast<const QueryConfigRequest*>(
               &_QueryConfigRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(QueryConfigRequest& a, QueryConfigRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryConfigRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryConfigRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryConfigRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QueryConfigRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const QueryConfigRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const QueryConfigRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "cosmos.app.v1alpha1.QueryConfigRequest";
  }
  protected:
  explicit QueryConfigRequest(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:cosmos.app.v1alpha1.QueryConfigRequest)
 private:
  class _Internal;

  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_cosmos_2fapp_2fv1alpha1_2fquery_2eproto;
};// -------------------------------------------------------------------

class QueryConfigResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cosmos.app.v1alpha1.QueryConfigResponse) */ {
 public:
  inline QueryConfigResponse() : QueryConfigResponse(nullptr) {}
  ~QueryConfigResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR QueryConfigResponse(::google::protobuf::internal::ConstantInitialized);

  QueryConfigResponse(const QueryConfigResponse& from);
  QueryConfigResponse(QueryConfigResponse&& from) noexcept
    : QueryConfigResponse() {
    *this = ::std::move(from);
  }

  inline QueryConfigResponse& operator=(const QueryConfigResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryConfigResponse& operator=(QueryConfigResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryConfigResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryConfigResponse* internal_default_instance() {
    return reinterpret_cast<const QueryConfigResponse*>(
               &_QueryConfigResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(QueryConfigResponse& a, QueryConfigResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryConfigResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryConfigResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryConfigResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QueryConfigResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QueryConfigResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const QueryConfigResponse& from) {
    QueryConfigResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryConfigResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "cosmos.app.v1alpha1.QueryConfigResponse";
  }
  protected:
  explicit QueryConfigResponse(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConfigFieldNumber = 1,
  };
  // .cosmos.app.v1alpha1.Config config = 1 [json_name = "config"];
  bool has_config() const;
  void clear_config() ;
  const ::cosmos::app::v1alpha1::Config& config() const;
  PROTOBUF_NODISCARD ::cosmos::app::v1alpha1::Config* release_config();
  ::cosmos::app::v1alpha1::Config* mutable_config();
  void set_allocated_config(::cosmos::app::v1alpha1::Config* value);
  void unsafe_arena_set_allocated_config(::cosmos::app::v1alpha1::Config* value);
  ::cosmos::app::v1alpha1::Config* unsafe_arena_release_config();

  private:
  const ::cosmos::app::v1alpha1::Config& _internal_config() const;
  ::cosmos::app::v1alpha1::Config* _internal_mutable_config();

  public:
  // @@protoc_insertion_point(class_scope:cosmos.app.v1alpha1.QueryConfigResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1, 1, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::cosmos::app::v1alpha1::Config* config_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cosmos_2fapp_2fv1alpha1_2fquery_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// QueryConfigRequest

// -------------------------------------------------------------------

// QueryConfigResponse

// .cosmos.app.v1alpha1.Config config = 1 [json_name = "config"];
inline bool QueryConfigResponse::has_config() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.config_ != nullptr);
  return value;
}
inline const ::cosmos::app::v1alpha1::Config& QueryConfigResponse::_internal_config() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::cosmos::app::v1alpha1::Config* p = _impl_.config_;
  return p != nullptr ? *p : reinterpret_cast<const ::cosmos::app::v1alpha1::Config&>(::cosmos::app::v1alpha1::_Config_default_instance_);
}
inline const ::cosmos::app::v1alpha1::Config& QueryConfigResponse::config() const {
  // @@protoc_insertion_point(field_get:cosmos.app.v1alpha1.QueryConfigResponse.config)
  return _internal_config();
}
inline void QueryConfigResponse::unsafe_arena_set_allocated_config(::cosmos::app::v1alpha1::Config* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.config_);
  }
  _impl_.config_ = reinterpret_cast<::cosmos::app::v1alpha1::Config*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cosmos.app.v1alpha1.QueryConfigResponse.config)
}
inline ::cosmos::app::v1alpha1::Config* QueryConfigResponse::release_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::cosmos::app::v1alpha1::Config* released = _impl_.config_;
  _impl_.config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::cosmos::app::v1alpha1::Config* QueryConfigResponse::unsafe_arena_release_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:cosmos.app.v1alpha1.QueryConfigResponse.config)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::cosmos::app::v1alpha1::Config* temp = _impl_.config_;
  _impl_.config_ = nullptr;
  return temp;
}
inline ::cosmos::app::v1alpha1::Config* QueryConfigResponse::_internal_mutable_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.config_ == nullptr) {
    auto* p = CreateMaybeMessage<::cosmos::app::v1alpha1::Config>(GetArenaForAllocation());
    _impl_.config_ = reinterpret_cast<::cosmos::app::v1alpha1::Config*>(p);
  }
  return _impl_.config_;
}
inline ::cosmos::app::v1alpha1::Config* QueryConfigResponse::mutable_config() {
  ::cosmos::app::v1alpha1::Config* _msg = _internal_mutable_config();
  // @@protoc_insertion_point(field_mutable:cosmos.app.v1alpha1.QueryConfigResponse.config)
  return _msg;
}
inline void QueryConfigResponse::set_allocated_config(::cosmos::app::v1alpha1::Config* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.config_ = reinterpret_cast<::cosmos::app::v1alpha1::Config*>(value);
  // @@protoc_insertion_point(field_set_allocated:cosmos.app.v1alpha1.QueryConfigResponse.config)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1alpha1
}  // namespace app
}  // namespace cosmos


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_cosmos_2fapp_2fv1alpha1_2fquery_2eproto_2epb_2eh
