// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cosmos/staking/v1beta1/query.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cosmos.staking.v1beta1;

@kotlin.jvm.JvmName("-initializequeryValidatorsResponse")
public inline fun queryValidatorsResponse(block: cosmos.staking.v1beta1.QueryValidatorsResponseKt.Dsl.() -> kotlin.Unit): cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponse =
  cosmos.staking.v1beta1.QueryValidatorsResponseKt.Dsl._create(cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * QueryValidatorsResponse is response type for the Query/Validators RPC method
 * ```
 *
 * Protobuf type `cosmos.staking.v1beta1.QueryValidatorsResponse`
 */
public object QueryValidatorsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ValidatorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * validators contains all the queried validators.
     * ```
     *
     * `repeated .cosmos.staking.v1beta1.Validator validators = 1 [json_name = "validators", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     */
     public val validators: com.google.protobuf.kotlin.DslList<cosmos.staking.v1beta1.Staking.Validator, ValidatorsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.validatorsList
      )
    /**
     * ```
     * validators contains all the queried validators.
     * ```
     *
     * `repeated .cosmos.staking.v1beta1.Validator validators = 1 [json_name = "validators", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param value The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addValidators")
    public fun com.google.protobuf.kotlin.DslList<cosmos.staking.v1beta1.Staking.Validator, ValidatorsProxy>.add(value: cosmos.staking.v1beta1.Staking.Validator) {
      _builder.addValidators(value)
    }
    /**
     * ```
     * validators contains all the queried validators.
     * ```
     *
     * `repeated .cosmos.staking.v1beta1.Validator validators = 1 [json_name = "validators", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param value The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignValidators")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<cosmos.staking.v1beta1.Staking.Validator, ValidatorsProxy>.plusAssign(value: cosmos.staking.v1beta1.Staking.Validator) {
      add(value)
    }
    /**
     * ```
     * validators contains all the queried validators.
     * ```
     *
     * `repeated .cosmos.staking.v1beta1.Validator validators = 1 [json_name = "validators", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param values The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllValidators")
    public fun com.google.protobuf.kotlin.DslList<cosmos.staking.v1beta1.Staking.Validator, ValidatorsProxy>.addAll(values: kotlin.collections.Iterable<cosmos.staking.v1beta1.Staking.Validator>) {
      _builder.addAllValidators(values)
    }
    /**
     * ```
     * validators contains all the queried validators.
     * ```
     *
     * `repeated .cosmos.staking.v1beta1.Validator validators = 1 [json_name = "validators", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param values The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllValidators")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<cosmos.staking.v1beta1.Staking.Validator, ValidatorsProxy>.plusAssign(values: kotlin.collections.Iterable<cosmos.staking.v1beta1.Staking.Validator>) {
      addAll(values)
    }
    /**
     * ```
     * validators contains all the queried validators.
     * ```
     *
     * `repeated .cosmos.staking.v1beta1.Validator validators = 1 [json_name = "validators", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param index The index to set the value at.
     * @param value The validators to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setValidators")
    public operator fun com.google.protobuf.kotlin.DslList<cosmos.staking.v1beta1.Staking.Validator, ValidatorsProxy>.set(index: kotlin.Int, value: cosmos.staking.v1beta1.Staking.Validator) {
      _builder.setValidators(index, value)
    }
    /**
     * ```
     * validators contains all the queried validators.
     * ```
     *
     * `repeated .cosmos.staking.v1beta1.Validator validators = 1 [json_name = "validators", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearValidators")
    public fun com.google.protobuf.kotlin.DslList<cosmos.staking.v1beta1.Staking.Validator, ValidatorsProxy>.clear() {
      _builder.clearValidators()
    }

    /**
     * ```
     * pagination defines the pagination in the response.
     * ```
     *
     * `.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];`
     */
    public var pagination: cosmos.base.query.v1beta1.Pagination.PageResponse
      @kotlin.jvm.JvmName("getPagination")
        get() = _builder.pagination
      @kotlin.jvm.JvmName("setPagination")
        set(value) {
        _builder.pagination = value
      }
    /**
     * ```
     * pagination defines the pagination in the response.
     * ```
     *
     * `.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];`
     */
    public fun clearPagination() {
      _builder.clearPagination()
    }
    /**
     * ```
     * pagination defines the pagination in the response.
     * ```
     *
     * `.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];`
     * @return Whether the pagination field is set.
     */
    public fun hasPagination(): kotlin.Boolean {
      return _builder.hasPagination()
    }

    public val QueryValidatorsResponseKt.Dsl.paginationOrNull: cosmos.base.query.v1beta1.Pagination.PageResponse?
      get() = _builder.paginationOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponse.copy(block: `cosmos.staking.v1beta1`.QueryValidatorsResponseKt.Dsl.() -> kotlin.Unit): cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponse =
  `cosmos.staking.v1beta1`.QueryValidatorsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val cosmos.staking.v1beta1.QueryOuterClass.QueryValidatorsResponseOrBuilder.paginationOrNull: cosmos.base.query.v1beta1.Pagination.PageResponse?
  get() = if (hasPagination()) getPagination() else null

