// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cosmos/genutil/v1beta1/genesis.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cosmos.genutil.v1beta1;

