// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: cosmos/app/runtime/v1alpha1/module.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class StoreKeyConfig;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ModuleRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ModuleRoot : GPBRootObject
@end

#pragma mark - Module

typedef GPB_ENUM(Module_FieldNumber) {
  Module_FieldNumber_AppName = 1,
  Module_FieldNumber_BeginBlockersArray = 2,
  Module_FieldNumber_EndBlockersArray = 3,
  Module_FieldNumber_InitGenesisArray = 4,
  Module_FieldNumber_ExportGenesisArray = 5,
  Module_FieldNumber_OverrideStoreKeysArray = 6,
  Module_FieldNumber_OrderMigrationsArray = 7,
  Module_FieldNumber_PrecommitersArray = 8,
  Module_FieldNumber_PrepareCheckStatersArray = 9,
  Module_FieldNumber_PreBlockersArray = 10,
  Module_FieldNumber_SkipStoreKeysArray = 11,
};

/**
 * Module is the config object for the runtime module.
 **/
GPB_FINAL @interface Module : GPBMessage

/** app_name is the name of the app. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;

/**
 * begin_blockers specifies the module names of begin blockers
 * to call in the order in which they should be called. If this is left empty
 * no begin blocker will be registered.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *beginBlockersArray;
/** The number of items in @c beginBlockersArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger beginBlockersArray_Count;

/**
 * end_blockers specifies the module names of the end blockers
 * to call in the order in which they should be called. If this is left empty
 * no end blocker will be registered.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *endBlockersArray;
/** The number of items in @c endBlockersArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger endBlockersArray_Count;

/**
 * init_genesis specifies the module names of init genesis functions
 * to call in the order in which they should be called. If this is left empty
 * no init genesis function will be registered.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *initGenesisArray;
/** The number of items in @c initGenesisArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger initGenesisArray_Count;
- (NSMutableArray<NSString*> *)initGenesisArray GPB_METHOD_FAMILY_NONE;

/**
 * export_genesis specifies the order in which to export module genesis data.
 * If this is left empty, the init_genesis order will be used for export genesis
 * if it is specified.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *exportGenesisArray;
/** The number of items in @c exportGenesisArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger exportGenesisArray_Count;

/**
 * override_store_keys is an optional list of overrides for the module store keys
 * to be used in keeper construction.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<StoreKeyConfig*> *overrideStoreKeysArray;
/** The number of items in @c overrideStoreKeysArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger overrideStoreKeysArray_Count;

/**
 * skip_store_keys is an optional list of store keys to skip when constructing the
 * module's keeper. This is useful when a module does not have a store key.
 * NOTE: the provided environment variable will have a fake store service.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *skipStoreKeysArray;
/** The number of items in @c skipStoreKeysArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger skipStoreKeysArray_Count;

/**
 * order_migrations defines the order in which module migrations are performed.
 * If this is left empty, it uses the default migration order.
 * https://pkg.go.dev/github.com/cosmos/cosmos-sdk/types/module#DefaultMigrationsOrder
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *orderMigrationsArray;
/** The number of items in @c orderMigrationsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger orderMigrationsArray_Count;

/**
 * precommiters specifies the module names of the precommiters
 * to call in the order in which they should be called. If this is left empty
 * no precommit function will be registered.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *precommitersArray;
/** The number of items in @c precommitersArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger precommitersArray_Count;

/**
 * prepare_check_staters specifies the module names of the prepare_check_staters
 * to call in the order in which they should be called. If this is left empty
 * no preparecheckstate function will be registered.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *prepareCheckStatersArray;
/** The number of items in @c prepareCheckStatersArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger prepareCheckStatersArray_Count;

/**
 * pre_blockers specifies the module names of pre blockers
 * to call in the order in which they should be called. If this is left empty
 * no pre blocker will be registered.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *preBlockersArray;
/** The number of items in @c preBlockersArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger preBlockersArray_Count;

@end

#pragma mark - StoreKeyConfig

typedef GPB_ENUM(StoreKeyConfig_FieldNumber) {
  StoreKeyConfig_FieldNumber_ModuleName = 1,
  StoreKeyConfig_FieldNumber_KvStoreKey = 2,
};

/**
 * StoreKeyConfig may be supplied to override the default module store key, which
 * is the module name.
 **/
GPB_FINAL @interface StoreKeyConfig : GPBMessage

/** name of the module to override the store key of */
@property(nonatomic, readwrite, copy, null_resettable) NSString *moduleName;

/** the kv store key to use instead of the module name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *kvStoreKey;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
