// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package cosmos.mint.v1beta1

object QueryProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.GogoProto,
    com.google.api.AnnotationsProto,
    cosmos.mint.v1beta1.MintProto,
    amino.AminoProto,
    cosmos_proto.CosmosProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      cosmos.mint.v1beta1.QueryParamsRequest,
      cosmos.mint.v1beta1.QueryParamsResponse,
      cosmos.mint.v1beta1.QueryInflationRequest,
      cosmos.mint.v1beta1.QueryInflationResponse,
      cosmos.mint.v1beta1.QueryAnnualProvisionsRequest,
      cosmos.mint.v1beta1.QueryAnnualProvisionsResponse
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ch9jb3Ntb3MvbWludC92MWJldGExL3F1ZXJ5LnByb3RvEhNjb3Ntb3MubWludC52MWJldGExGhRnb2dvcHJvdG8vZ29nby5wc
  m90bxocZ29vZ2xlL2FwaS9hbm5vdGF0aW9ucy5wcm90bxoeY29zbW9zL21pbnQvdjFiZXRhMS9taW50LnByb3RvGhFhbWluby9hb
  Wluby5wcm90bxoZY29zbW9zX3Byb3RvL2Nvc21vcy5wcm90byIUChJRdWVyeVBhcmFtc1JlcXVlc3QiYAoTUXVlcnlQYXJhbXNSZ
  XNwb25zZRJJCgZwYXJhbXMYASABKAsyGy5jb3Ntb3MubWludC52MWJldGExLlBhcmFtc0IU4j8IEgZwYXJhbXPI3h8AqOewKgFSB
  nBhcmFtcyIXChVRdWVyeUluZmxhdGlvblJlcXVlc3QifAoWUXVlcnlJbmZsYXRpb25SZXNwb25zZRJiCglpbmZsYXRpb24YASABK
  AxCROI/CxIJaW5mbGF0aW9uyN4fANreHxtjb3Ntb3NzZGsuaW8vbWF0aC5MZWdhY3lEZWPStC0KY29zbW9zLkRlY6jnsCoBUglpb
  mZsYXRpb24iHgocUXVlcnlBbm51YWxQcm92aXNpb25zUmVxdWVzdCKZAQodUXVlcnlBbm51YWxQcm92aXNpb25zUmVzcG9uc2USe
  AoRYW5udWFsX3Byb3Zpc2lvbnMYASABKAxCS+I/EhIQYW5udWFsUHJvdmlzaW9uc8jeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguT
  GVnYWN5RGVj0rQtCmNvc21vcy5EZWOo57AqAVIQYW5udWFsUHJvdmlzaW9uczLFAwoFUXVlcnkSgAEKBlBhcmFtcxInLmNvc21vc
  y5taW50LnYxYmV0YTEuUXVlcnlQYXJhbXNSZXF1ZXN0GiguY29zbW9zLm1pbnQudjFiZXRhMS5RdWVyeVBhcmFtc1Jlc3BvbnNlI
  iOC0+STAh0SGy9jb3Ntb3MvbWludC92MWJldGExL3BhcmFtcxKMAQoJSW5mbGF0aW9uEiouY29zbW9zLm1pbnQudjFiZXRhMS5Rd
  WVyeUluZmxhdGlvblJlcXVlc3QaKy5jb3Ntb3MubWludC52MWJldGExLlF1ZXJ5SW5mbGF0aW9uUmVzcG9uc2UiJoLT5JMCIBIeL
  2Nvc21vcy9taW50L3YxYmV0YTEvaW5mbGF0aW9uEqkBChBBbm51YWxQcm92aXNpb25zEjEuY29zbW9zLm1pbnQudjFiZXRhMS5Rd
  WVyeUFubnVhbFByb3Zpc2lvbnNSZXF1ZXN0GjIuY29zbW9zLm1pbnQudjFiZXRhMS5RdWVyeUFubnVhbFByb3Zpc2lvbnNSZXNwb
  25zZSIugtPkkwIoEiYvY29zbW9zL21pbnQvdjFiZXRhMS9hbm51YWxfcHJvdmlzaW9uc0IrWilnaXRodWIuY29tL2Nvc21vcy9jb
  3Ntb3Mtc2RrL3gvbWludC90eXBlc2IGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      com.google.protobuf.GogoProto.javaDescriptor,
      com.google.api.AnnotationsProto.javaDescriptor,
      cosmos.mint.v1beta1.MintProto.javaDescriptor,
      amino.AminoProto.javaDescriptor,
      cosmos_proto.CosmosProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}