// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cosmwasm/wasm/v1/tx.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cosmwasm.wasm.v1;

@kotlin.jvm.JvmName("-initializemsgUpdateParamsResponse")
public inline fun msgUpdateParamsResponse(block: cosmwasm.wasm.v1.MsgUpdateParamsResponseKt.Dsl.() -> kotlin.Unit): cosmwasm.wasm.v1.Tx.MsgUpdateParamsResponse =
  cosmwasm.wasm.v1.MsgUpdateParamsResponseKt.Dsl._create(cosmwasm.wasm.v1.Tx.MsgUpdateParamsResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * Since: 0.40
 * ```
 *
 * Protobuf type `cosmwasm.wasm.v1.MsgUpdateParamsResponse`
 */
public object MsgUpdateParamsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cosmwasm.wasm.v1.Tx.MsgUpdateParamsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: cosmwasm.wasm.v1.Tx.MsgUpdateParamsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): cosmwasm.wasm.v1.Tx.MsgUpdateParamsResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cosmwasm.wasm.v1.Tx.MsgUpdateParamsResponse.copy(block: `cosmwasm.wasm.v1`.MsgUpdateParamsResponseKt.Dsl.() -> kotlin.Unit): cosmwasm.wasm.v1.Tx.MsgUpdateParamsResponse =
  `cosmwasm.wasm.v1`.MsgUpdateParamsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

