// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cosmwasm/wasm/v1/authz.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cosmwasm.wasm.v1;

@kotlin.jvm.JvmName("-initializestoreCodeAuthorization")
public inline fun storeCodeAuthorization(block: cosmwasm.wasm.v1.StoreCodeAuthorizationKt.Dsl.() -> kotlin.Unit): cosmwasm.wasm.v1.Authz.StoreCodeAuthorization =
  cosmwasm.wasm.v1.StoreCodeAuthorizationKt.Dsl._create(cosmwasm.wasm.v1.Authz.StoreCodeAuthorization.newBuilder()).apply { block() }._build()
/**
 * ```
 * StoreCodeAuthorization defines authorization for wasm code upload.
 * Since: wasmd 0.42
 * ```
 *
 * Protobuf type `cosmwasm.wasm.v1.StoreCodeAuthorization`
 */
public object StoreCodeAuthorizationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cosmwasm.wasm.v1.Authz.StoreCodeAuthorization.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: cosmwasm.wasm.v1.Authz.StoreCodeAuthorization.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): cosmwasm.wasm.v1.Authz.StoreCodeAuthorization = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GrantsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Grants for code upload
     * ```
     *
     * `repeated .cosmwasm.wasm.v1.CodeGrant grants = 1 [json_name = "grants", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     */
     public val grants: com.google.protobuf.kotlin.DslList<cosmwasm.wasm.v1.Authz.CodeGrant, GrantsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.grantsList
      )
    /**
     * ```
     * Grants for code upload
     * ```
     *
     * `repeated .cosmwasm.wasm.v1.CodeGrant grants = 1 [json_name = "grants", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param value The grants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addGrants")
    public fun com.google.protobuf.kotlin.DslList<cosmwasm.wasm.v1.Authz.CodeGrant, GrantsProxy>.add(value: cosmwasm.wasm.v1.Authz.CodeGrant) {
      _builder.addGrants(value)
    }
    /**
     * ```
     * Grants for code upload
     * ```
     *
     * `repeated .cosmwasm.wasm.v1.CodeGrant grants = 1 [json_name = "grants", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param value The grants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignGrants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<cosmwasm.wasm.v1.Authz.CodeGrant, GrantsProxy>.plusAssign(value: cosmwasm.wasm.v1.Authz.CodeGrant) {
      add(value)
    }
    /**
     * ```
     * Grants for code upload
     * ```
     *
     * `repeated .cosmwasm.wasm.v1.CodeGrant grants = 1 [json_name = "grants", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param values The grants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllGrants")
    public fun com.google.protobuf.kotlin.DslList<cosmwasm.wasm.v1.Authz.CodeGrant, GrantsProxy>.addAll(values: kotlin.collections.Iterable<cosmwasm.wasm.v1.Authz.CodeGrant>) {
      _builder.addAllGrants(values)
    }
    /**
     * ```
     * Grants for code upload
     * ```
     *
     * `repeated .cosmwasm.wasm.v1.CodeGrant grants = 1 [json_name = "grants", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param values The grants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllGrants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<cosmwasm.wasm.v1.Authz.CodeGrant, GrantsProxy>.plusAssign(values: kotlin.collections.Iterable<cosmwasm.wasm.v1.Authz.CodeGrant>) {
      addAll(values)
    }
    /**
     * ```
     * Grants for code upload
     * ```
     *
     * `repeated .cosmwasm.wasm.v1.CodeGrant grants = 1 [json_name = "grants", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     * @param index The index to set the value at.
     * @param value The grants to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setGrants")
    public operator fun com.google.protobuf.kotlin.DslList<cosmwasm.wasm.v1.Authz.CodeGrant, GrantsProxy>.set(index: kotlin.Int, value: cosmwasm.wasm.v1.Authz.CodeGrant) {
      _builder.setGrants(index, value)
    }
    /**
     * ```
     * Grants for code upload
     * ```
     *
     * `repeated .cosmwasm.wasm.v1.CodeGrant grants = 1 [json_name = "grants", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearGrants")
    public fun com.google.protobuf.kotlin.DslList<cosmwasm.wasm.v1.Authz.CodeGrant, GrantsProxy>.clear() {
      _builder.clearGrants()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cosmwasm.wasm.v1.Authz.StoreCodeAuthorization.copy(block: `cosmwasm.wasm.v1`.StoreCodeAuthorizationKt.Dsl.() -> kotlin.Unit): cosmwasm.wasm.v1.Authz.StoreCodeAuthorization =
  `cosmwasm.wasm.v1`.StoreCodeAuthorizationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

