// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package cosmos.group.v1

/** MsgCreateGroupPolicy is the Msg/CreateGroupPolicy request type.
  *
  * @param admin
  *   admin is the account address of the group admin.
  * @param groupId
  *   group_id is the unique ID of the group.
  * @param metadata
  *   metadata is any arbitrary metadata attached to the group policy.
  * @param decisionPolicy
  *   decision_policy specifies the group policy's decision policy.
  */
@SerialVersionUID(0L)
final case class MsgCreateGroupPolicy(
    admin: _root_.scala.Predef.String = "",
    groupId: _root_.scala.Long = 0L,
    metadata: _root_.scala.Predef.String = "",
    decisionPolicy: _root_.scala.Option[com.google.protobuf.any.Any] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[MsgCreateGroupPolicy] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = admin
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = groupId
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(2, __value)
        }
      };
      
      {
        val __value = metadata
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      if (decisionPolicy.isDefined) {
        val __value = decisionPolicy.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = admin
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = groupId
        if (__v != 0L) {
          _output__.writeUInt64(2, __v)
        }
      };
      {
        val __v = metadata
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      decisionPolicy.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withAdmin(__v: _root_.scala.Predef.String): MsgCreateGroupPolicy = copy(admin = __v)
    def withGroupId(__v: _root_.scala.Long): MsgCreateGroupPolicy = copy(groupId = __v)
    def withMetadata(__v: _root_.scala.Predef.String): MsgCreateGroupPolicy = copy(metadata = __v)
    def getDecisionPolicy: com.google.protobuf.any.Any = decisionPolicy.getOrElse(com.google.protobuf.any.Any.defaultInstance)
    def clearDecisionPolicy: MsgCreateGroupPolicy = copy(decisionPolicy = _root_.scala.None)
    def withDecisionPolicy(__v: com.google.protobuf.any.Any): MsgCreateGroupPolicy = copy(decisionPolicy = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = admin
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = groupId
          if (__t != 0L) __t else null
        }
        case 3 => {
          val __t = metadata
          if (__t != "") __t else null
        }
        case 4 => decisionPolicy.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(admin)
        case 2 => _root_.scalapb.descriptors.PLong(groupId)
        case 3 => _root_.scalapb.descriptors.PString(metadata)
        case 4 => decisionPolicy.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: cosmos.group.v1.MsgCreateGroupPolicy.type = cosmos.group.v1.MsgCreateGroupPolicy
    // @@protoc_insertion_point(GeneratedMessage[cosmos.group.v1.MsgCreateGroupPolicy])
}

object MsgCreateGroupPolicy extends scalapb.GeneratedMessageCompanion[cosmos.group.v1.MsgCreateGroupPolicy] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[cosmos.group.v1.MsgCreateGroupPolicy] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): cosmos.group.v1.MsgCreateGroupPolicy = {
    var __admin: _root_.scala.Predef.String = ""
    var __groupId: _root_.scala.Long = 0L
    var __metadata: _root_.scala.Predef.String = ""
    var __decisionPolicy: _root_.scala.Option[com.google.protobuf.any.Any] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __admin = _input__.readStringRequireUtf8()
        case 16 =>
          __groupId = _input__.readUInt64()
        case 26 =>
          __metadata = _input__.readStringRequireUtf8()
        case 34 =>
          __decisionPolicy = _root_.scala.Option(__decisionPolicy.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.any.Any](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    cosmos.group.v1.MsgCreateGroupPolicy(
        admin = __admin,
        groupId = __groupId,
        metadata = __metadata,
        decisionPolicy = __decisionPolicy,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[cosmos.group.v1.MsgCreateGroupPolicy] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      cosmos.group.v1.MsgCreateGroupPolicy(
        admin = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        groupId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        metadata = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        decisionPolicy = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.any.Any]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = cosmos.group.v1.TxProto.javaDescriptor.getMessageTypes().get(8)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = cosmos.group.v1.TxProto.scalaDescriptor.messages(8)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = com.google.protobuf.any.Any
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = cosmos.group.v1.MsgCreateGroupPolicy(
    admin = "",
    groupId = 0L,
    metadata = "",
    decisionPolicy = _root_.scala.None
  )
  implicit class MsgCreateGroupPolicyLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, cosmos.group.v1.MsgCreateGroupPolicy]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, cosmos.group.v1.MsgCreateGroupPolicy](_l) {
    def admin: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.admin)((c_, f_) => c_.copy(admin = f_))
    def groupId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.groupId)((c_, f_) => c_.copy(groupId = f_))
    def metadata: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.metadata)((c_, f_) => c_.copy(metadata = f_))
    def decisionPolicy: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.any.Any] = field(_.getDecisionPolicy)((c_, f_) => c_.copy(decisionPolicy = _root_.scala.Option(f_)))
    def optionalDecisionPolicy: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.any.Any]] = field(_.decisionPolicy)((c_, f_) => c_.copy(decisionPolicy = f_))
  }
  final val ADMIN_FIELD_NUMBER = 1
  final val GROUP_ID_FIELD_NUMBER = 2
  final val METADATA_FIELD_NUMBER = 3
  final val DECISION_POLICY_FIELD_NUMBER = 4
  def of(
    admin: _root_.scala.Predef.String,
    groupId: _root_.scala.Long,
    metadata: _root_.scala.Predef.String,
    decisionPolicy: _root_.scala.Option[com.google.protobuf.any.Any]
  ): _root_.cosmos.group.v1.MsgCreateGroupPolicy = _root_.cosmos.group.v1.MsgCreateGroupPolicy(
    admin,
    groupId,
    metadata,
    decisionPolicy
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[cosmos.group.v1.MsgCreateGroupPolicy])
}
