// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xion/v1/tx.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package xion.v1;

@kotlin.jvm.JvmName("-initializemsgSetPlatformPercentage")
public inline fun msgSetPlatformPercentage(block: xion.v1.MsgSetPlatformPercentageKt.Dsl.() -> kotlin.Unit): xion.v1.Tx.MsgSetPlatformPercentage =
  xion.v1.MsgSetPlatformPercentageKt.Dsl._create(xion.v1.Tx.MsgSetPlatformPercentage.newBuilder()).apply { block() }._build()
/**
 * ```
 * MsgSetPlatformPercentage defines the message for setting platform percentage
 * ```
 *
 * Protobuf type `xion.v1.MsgSetPlatformPercentage`
 */
public object MsgSetPlatformPercentageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: xion.v1.Tx.MsgSetPlatformPercentage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: xion.v1.Tx.MsgSetPlatformPercentage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): xion.v1.Tx.MsgSetPlatformPercentage = _builder.build()

    /**
     * ```
     * The authority address that can set the platform percentage
     * ```
     *
     * `string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];`
     */
    public var authority: kotlin.String
      @kotlin.jvm.JvmName("getAuthority")
        get() = _builder.authority
      @kotlin.jvm.JvmName("setAuthority")
        set(value) {
        _builder.authority = value
      }
    /**
     * ```
     * The authority address that can set the platform percentage
     * ```
     *
     * `string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];`
     */
    public fun clearAuthority() {
      _builder.clearAuthority()
    }

    /**
     * ```
     * platform_percentage is the platform fee percentage to multiplied by 10000
     * ```
     *
     * `uint32 platform_percentage = 2 [json_name = "platformPercentage"];`
     */
    public var platformPercentage: kotlin.Int
      @kotlin.jvm.JvmName("getPlatformPercentage")
        get() = _builder.platformPercentage
      @kotlin.jvm.JvmName("setPlatformPercentage")
        set(value) {
        _builder.platformPercentage = value
      }
    /**
     * ```
     * platform_percentage is the platform fee percentage to multiplied by 10000
     * ```
     *
     * `uint32 platform_percentage = 2 [json_name = "platformPercentage"];`
     */
    public fun clearPlatformPercentage() {
      _builder.clearPlatformPercentage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun xion.v1.Tx.MsgSetPlatformPercentage.copy(block: `xion.v1`.MsgSetPlatformPercentageKt.Dsl.() -> kotlin.Unit): xion.v1.Tx.MsgSetPlatformPercentage =
  `xion.v1`.MsgSetPlatformPercentageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

