// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xion/v1/query.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package xion.v1;

@kotlin.jvm.JvmName("-initializequeryWebAuthNVerifyRegisterResponse")
public inline fun queryWebAuthNVerifyRegisterResponse(block: xion.v1.QueryWebAuthNVerifyRegisterResponseKt.Dsl.() -> kotlin.Unit): xion.v1.QueryOuterClass.QueryWebAuthNVerifyRegisterResponse =
  xion.v1.QueryWebAuthNVerifyRegisterResponseKt.Dsl._create(xion.v1.QueryOuterClass.QueryWebAuthNVerifyRegisterResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * QueryWebAuthNVerifyRegisterResponse is the response type for WebAuthN
 * registration verification
 * ```
 *
 * Protobuf type `xion.v1.QueryWebAuthNVerifyRegisterResponse`
 */
public object QueryWebAuthNVerifyRegisterResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: xion.v1.QueryOuterClass.QueryWebAuthNVerifyRegisterResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: xion.v1.QueryOuterClass.QueryWebAuthNVerifyRegisterResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): xion.v1.QueryOuterClass.QueryWebAuthNVerifyRegisterResponse = _builder.build()

    /**
     * ```
     * The generated credential
     * ```
     *
     * `bytes credential = 1 [json_name = "credential"];`
     */
    public var credential: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getCredential")
        get() = _builder.credential
      @kotlin.jvm.JvmName("setCredential")
        set(value) {
        _builder.credential = value
      }
    /**
     * ```
     * The generated credential
     * ```
     *
     * `bytes credential = 1 [json_name = "credential"];`
     */
    public fun clearCredential() {
      _builder.clearCredential()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun xion.v1.QueryOuterClass.QueryWebAuthNVerifyRegisterResponse.copy(block: `xion.v1`.QueryWebAuthNVerifyRegisterResponseKt.Dsl.() -> kotlin.Unit): xion.v1.QueryOuterClass.QueryWebAuthNVerifyRegisterResponse =
  `xion.v1`.QueryWebAuthNVerifyRegisterResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

