// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/distribution/v1beta1/query.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cosmos.distribution.v1beta1;

@kotlin.jvm.JvmName("-initializequeryValidatorHistoricalRewardsRequest")
public inline fun queryValidatorHistoricalRewardsRequest(block: cosmos.distribution.v1beta1.QueryValidatorHistoricalRewardsRequestKt.Dsl.() -> kotlin.Unit): cosmos.distribution.v1beta1.QueryOuterClass.QueryValidatorHistoricalRewardsRequest =
  cosmos.distribution.v1beta1.QueryValidatorHistoricalRewardsRequestKt.Dsl._create(cosmos.distribution.v1beta1.QueryOuterClass.QueryValidatorHistoricalRewardsRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * QueryValidatorHistoricalRewardsRequest is the request type for the
 * Query/ValidatorHistoricalRewards RPC method.
 * ```
 *
 * Protobuf type `cosmos.distribution.v1beta1.QueryValidatorHistoricalRewardsRequest`
 */
public object QueryValidatorHistoricalRewardsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cosmos.distribution.v1beta1.QueryOuterClass.QueryValidatorHistoricalRewardsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.distribution.v1beta1.QueryOuterClass.QueryValidatorHistoricalRewardsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.distribution.v1beta1.QueryOuterClass.QueryValidatorHistoricalRewardsRequest = _builder.build()

    /**
     * ```
     * validator_address defines the validator address to query for.
     * ```
     *
     * `string validator_address = 1 [json_name = "validatorAddress", (.cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];`
     */
    public var validatorAddress: kotlin.String
      @JvmName("getValidatorAddress")
      get() = _builder.getValidatorAddress()
      @JvmName("setValidatorAddress")
      set(value) {
        _builder.setValidatorAddress(value)
      }
    /**
     * ```
     * validator_address defines the validator address to query for.
     * ```
     *
     * `string validator_address = 1 [json_name = "validatorAddress", (.cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];`
     */
    public fun clearValidatorAddress() {
      _builder.clearValidatorAddress()
    }

    /**
     * ```
     * period defines the period to query historical rewards for.
     * ```
     *
     * `uint64 period = 2 [json_name = "period"];`
     */
    public var period: kotlin.Long
      @JvmName("getPeriod")
      get() = _builder.getPeriod()
      @JvmName("setPeriod")
      set(value) {
        _builder.setPeriod(value)
      }
    /**
     * ```
     * period defines the period to query historical rewards for.
     * ```
     *
     * `uint64 period = 2 [json_name = "period"];`
     */
    public fun clearPeriod() {
      _builder.clearPeriod()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cosmos.distribution.v1beta1.QueryOuterClass.QueryValidatorHistoricalRewardsRequest.copy(block: cosmos.distribution.v1beta1.QueryValidatorHistoricalRewardsRequestKt.Dsl.() -> kotlin.Unit): cosmos.distribution.v1beta1.QueryOuterClass.QueryValidatorHistoricalRewardsRequest =
  cosmos.distribution.v1beta1.QueryValidatorHistoricalRewardsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

