// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package ibc.applications.transfer.v1

object GenesisProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    ibc.applications.transfer.v1.TransferProto,
    ibc.applications.transfer.v1.TokenProto,
    cosmos.base.v1beta1.CoinProto,
    com.google.protobuf.GogoProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      ibc.applications.transfer.v1.GenesisState
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CippYmMvYXBwbGljYXRpb25zL3RyYW5zZmVyL3YxL2dlbmVzaXMucHJvdG8SHGliYy5hcHBsaWNhdGlvbnMudHJhbnNmZXIud
  jEaK2liYy9hcHBsaWNhdGlvbnMvdHJhbnNmZXIvdjEvdHJhbnNmZXIucHJvdG8aKGliYy9hcHBsaWNhdGlvbnMvdHJhbnNmZXIvd
  jEvdG9rZW4ucHJvdG8aHmNvc21vcy9iYXNlL3YxYmV0YTEvY29pbi5wcm90bxoUZ29nb3Byb3RvL2dvZ28ucHJvdG8i4gIKDEdlb
  mVzaXNTdGF0ZRIkCgdwb3J0X2lkGAEgASgJQgviPwgSBnBvcnRJZFIGcG9ydElkElYKBmRlbm9tcxgCIAMoCzIjLmliYy5hcHBsa
  WNhdGlvbnMudHJhbnNmZXIudjEuRGVub21CGeI/CBIGZGVub21zyN4fAKrfHwZEZW5vbXNSBmRlbm9tcxJNCgZwYXJhbXMYAyABK
  AsyJC5pYmMuYXBwbGljYXRpb25zLnRyYW5zZmVyLnYxLlBhcmFtc0IP4j8IEgZwYXJhbXPI3h8AUgZwYXJhbXMShAEKDnRvdGFsX
  2VzY3Jvd2VkGAQgAygLMhkuY29zbW9zLmJhc2UudjFiZXRhMS5Db2luQkLiPw8SDXRvdGFsRXNjcm93ZWTI3h8Aqt8fKGdpdGh1Y
  i5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXMuQ29pbnNSDXRvdGFsRXNjcm93ZWRCOlo4Z2l0aHViLmNvbS9jb3Ntb3MvaWJjL
  WdvL3YxMC9tb2R1bGVzL2FwcHMvdHJhbnNmZXIvdHlwZXNiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      ibc.applications.transfer.v1.TransferProto.javaDescriptor,
      ibc.applications.transfer.v1.TokenProto.javaDescriptor,
      cosmos.base.v1beta1.CoinProto.javaDescriptor,
      com.google.protobuf.GogoProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}