<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/authz/v1beta1/authz.proto

namespace GPBMetadata\Cosmos\Authz\V1Beta1;

class Authz
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Amino\Amino::initOnce();
        \GPBMetadata\CosmosProto\Cosmos::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Gogoproto\Gogo::initOnce();
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDE\x06\x0A cosmos/authz/v1beta1/authz.proto\x12\x14cosmos.authz.v1beta1\x1A\x19cosmos_proto/cosmos.proto\x1A\x1Fgoogle/protobuf/timestamp.proto\x1A\x14gogoproto/gogo.proto\x1A\x19google/protobuf/any.proto\"t\x0A\x14GenericAuthorization\x12\x10\x0A\x03msg\x18\x01 \x01(\x09R\x03msg:J\xCA\xB4-\"cosmos.authz.v1beta1.Authorization\x8A\xE7\xB0*\x1Fcosmos-sdk/GenericAuthorization\"\xB1\x01\x0A\x05Grant\x12b\x0A\x0Dauthorization\x18\x01 \x01(\x0B2\x14.google.protobuf.AnyB&\xCA\xB4-\"cosmos.authz.v1beta1.AuthorizationR\x0Dauthorization\x12D\x0A\x0Aexpiration\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampB\x08\xC8\xDE\x1F\x01\x90\xDF\x1F\x01R\x0Aexpiration\"\xA2\x02\x0A\x12GrantAuthorization\x122\x0A\x07granter\x18\x01 \x01(\x09B\x18\xD2\xB4-\x14cosmos.AddressStringR\x07granter\x122\x0A\x07grantee\x18\x02 \x01(\x09B\x18\xD2\xB4-\x14cosmos.AddressStringR\x07grantee\x12b\x0A\x0Dauthorization\x18\x03 \x01(\x0B2\x14.google.protobuf.AnyB&\xCA\xB4-\"cosmos.authz.v1beta1.AuthorizationR\x0Dauthorization\x12@\x0A\x0Aexpiration\x18\x04 \x01(\x0B2\x1A.google.protobuf.TimestampB\x04\x90\xDF\x1F\x01R\x0Aexpiration\"4\x0A\x0EGrantQueueItem\x12\"\x0A\x0Dmsg_type_urls\x18\x01 \x03(\x09R\x0BmsgTypeUrlsB*Z\$github.com/cosmos/cosmos-sdk/x/authz\xC8\xE1\x1E\x00b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

