# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/base/reflection/v1beta1/reflection.proto

require 'google/protobuf'

require 'google/api/annotations_pb'


descriptor_data = "\n/cosmos/base/reflection/v1beta1/reflection.proto\x12\x1e\x63osmos.base.reflection.v1beta1\x1a\x1cgoogle/api/annotations.proto\"\x1a\n\x18ListAllInterfacesRequest\"D\n\x19ListAllInterfacesResponse\x12\'\n\x0finterface_names\x18\x01 \x03(\tR\x0einterfaceNames\"C\n\x1aListImplementationsRequest\x12%\n\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\"_\n\x1bListImplementationsResponse\x12@\n\x1cimplementation_message_names\x18\x01 \x03(\tR\x1aimplementationMessageNames2\xb8\x03\n\x11ReflectionService\x12\xbc\x01\n\x11ListAllInterfaces\x12\x38.cosmos.base.reflection.v1beta1.ListAllInterfacesRequest\x1a\x39.cosmos.base.reflection.v1beta1.ListAllInterfacesResponse\"2\x82\xd3\xe4\x93\x02,\x12*/cosmos/base/reflection/v1beta1/interfaces\x12\xe3\x01\n\x13ListImplementations\x12:.cosmos.base.reflection.v1beta1.ListImplementationsRequest\x1a;.cosmos.base.reflection.v1beta1.ListImplementationsResponse\"S\x82\xd3\xe4\x93\x02M\x12K/cosmos/base/reflection/v1beta1/interfaces/{interface_name}/implementationsB5Z3github.com/cosmos/cosmos-sdk/client/grpc/reflectionb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Cosmos
  module Base
    module Reflection
      module V1beta1
        ListAllInterfacesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.base.reflection.v1beta1.ListAllInterfacesRequest").msgclass
        ListAllInterfacesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.base.reflection.v1beta1.ListAllInterfacesResponse").msgclass
        ListImplementationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.base.reflection.v1beta1.ListImplementationsRequest").msgclass
        ListImplementationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.base.reflection.v1beta1.ListImplementationsResponse").msgclass
      end
    end
  end
end
