// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cosmos/base/v1beta1/coin.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package cosmos.base.v1beta1;

@kotlin.jvm.JvmName("-initializecoin")
public inline fun coin(block: cosmos.base.v1beta1.CoinKt.Dsl.() -> kotlin.Unit): cosmos.base.v1beta1.CoinOuterClass.Coin =
  cosmos.base.v1beta1.CoinKt.Dsl._create(cosmos.base.v1beta1.CoinOuterClass.Coin.newBuilder()).apply { block() }._build()
/**
 * ```
 * Coin defines a token with a denomination and an amount.
 *
 * NOTE: The amount field is an Int which implements the custom method
 * signatures required by gogoproto.
 * ```
 *
 * Protobuf type `cosmos.base.v1beta1.Coin`
 */
public object CoinKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: cosmos.base.v1beta1.CoinOuterClass.Coin.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: cosmos.base.v1beta1.CoinOuterClass.Coin.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): cosmos.base.v1beta1.CoinOuterClass.Coin = _builder.build()

    /**
     * `string denom = 1 [json_name = "denom"];`
     */
    public var denom: kotlin.String
      @kotlin.jvm.JvmName("getDenom")
        get() = _builder.denom
      @kotlin.jvm.JvmName("setDenom")
        set(value) {
        _builder.denom = value
      }
    /**
     * `string denom = 1 [json_name = "denom"];`
     */
    public fun clearDenom() {
      _builder.clearDenom()
    }

    /**
     * `string amount = 2 [json_name = "amount", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "cosmossdk.io/math.Int", (.cosmos_proto.scalar) = "cosmos.Int", (.amino.dont_omitempty) = true];`
     */
    public var amount: kotlin.String
      @kotlin.jvm.JvmName("getAmount")
        get() = _builder.amount
      @kotlin.jvm.JvmName("setAmount")
        set(value) {
        _builder.amount = value
      }
    /**
     * `string amount = 2 [json_name = "amount", (.gogoproto.nullable) = false, (.gogoproto.customtype) = "cosmossdk.io/math.Int", (.cosmos_proto.scalar) = "cosmos.Int", (.amino.dont_omitempty) = true];`
     */
    public fun clearAmount() {
      _builder.clearAmount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun cosmos.base.v1beta1.CoinOuterClass.Coin.copy(block: `cosmos.base.v1beta1`.CoinKt.Dsl.() -> kotlin.Unit): cosmos.base.v1beta1.CoinOuterClass.Coin =
  `cosmos.base.v1beta1`.CoinKt.Dsl._create(this.toBuilder()).apply { block() }._build()

