// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xion/v1/feegrant.proto

#include "xion/v1/feegrant.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace xion {
namespace v1 {
        template <typename>
PROTOBUF_CONSTEXPR AuthzAllowance::AuthzAllowance(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.authz_grantee_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.allowance_)*/ nullptr,
    } {}
struct AuthzAllowanceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthzAllowanceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthzAllowanceDefaultTypeInternal() {}
  union {
    AuthzAllowance _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthzAllowanceDefaultTypeInternal _AuthzAllowance_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR ContractsAllowance::ContractsAllowance(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.contract_addresses_)*/ {},
      /*decltype(_impl_.allowance_)*/ nullptr,
    } {}
struct ContractsAllowanceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ContractsAllowanceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ContractsAllowanceDefaultTypeInternal() {}
  union {
    ContractsAllowance _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ContractsAllowanceDefaultTypeInternal _ContractsAllowance_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR MultiAnyAllowance::MultiAnyAllowance(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.allowances_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct MultiAnyAllowanceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MultiAnyAllowanceDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MultiAnyAllowanceDefaultTypeInternal() {}
  union {
    MultiAnyAllowance _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MultiAnyAllowanceDefaultTypeInternal _MultiAnyAllowance_default_instance_;
}  // namespace v1
}  // namespace xion
static ::_pb::Metadata file_level_metadata_xion_2fv1_2ffeegrant_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_xion_2fv1_2ffeegrant_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_xion_2fv1_2ffeegrant_2eproto = nullptr;
const ::uint32_t TableStruct_xion_2fv1_2ffeegrant_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::xion::v1::AuthzAllowance, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::xion::v1::AuthzAllowance, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xion::v1::AuthzAllowance, _impl_.allowance_),
    PROTOBUF_FIELD_OFFSET(::xion::v1::AuthzAllowance, _impl_.authz_grantee_),
    0,
    ~0u,
    PROTOBUF_FIELD_OFFSET(::xion::v1::ContractsAllowance, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::xion::v1::ContractsAllowance, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xion::v1::ContractsAllowance, _impl_.allowance_),
    PROTOBUF_FIELD_OFFSET(::xion::v1::ContractsAllowance, _impl_.contract_addresses_),
    0,
    ~0u,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::xion::v1::MultiAnyAllowance, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xion::v1::MultiAnyAllowance, _impl_.allowances_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::xion::v1::AuthzAllowance)},
        {12, 22, -1, sizeof(::xion::v1::ContractsAllowance)},
        {24, -1, -1, sizeof(::xion::v1::MultiAnyAllowance)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::xion::v1::_AuthzAllowance_default_instance_._instance,
    &::xion::v1::_ContractsAllowance_default_instance_._instance,
    &::xion::v1::_MultiAnyAllowance_default_instance_._instance,
};
const char descriptor_table_protodef_xion_2fv1_2ffeegrant_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\026xion/v1/feegrant.proto\022\007xion.v1\032\024gogop"
    "roto/gogo.proto\032\031google/protobuf/any.pro"
    "to\032\031cosmos_proto/cosmos.proto\032\021amino/ami"
    "no.proto\"\365\001\n\016AuthzAllowance\022]\n\tallowance"
    "\030\001 \001(\0132\024.google.protobuf.AnyB)\312\264-%cosmos"
    ".feegrant.v1beta1.FeeAllowanceIR\tallowan"
    "ce\022=\n\rauthz_grantee\030\002 \001(\tB\030\322\264-\024cosmos.Ad"
    "dressStringR\014authzGrantee:E\210\240\037\000\312\264-%cosmo"
    "s.feegrant.v1beta1.FeeAllowanceI\212\347\260*\023xio"
    "n/AuthzAllowance\"\207\002\n\022ContractsAllowance\022"
    "]\n\tallowance\030\001 \001(\0132\024.google.protobuf.Any"
    "B)\312\264-%cosmos.feegrant.v1beta1.FeeAllowan"
    "ceIR\tallowance\022G\n\022contract_addresses\030\002 \003"
    "(\tB\030\322\264-\024cosmos.AddressStringR\021contractAd"
    "dresses:I\210\240\037\000\312\264-%cosmos.feegrant.v1beta1"
    ".FeeAllowanceI\212\347\260*\027xion/ContractsAllowan"
    "ce\"\276\001\n\021MultiAnyAllowance\022_\n\nallowances\030\001"
    " \003(\0132\024.google.protobuf.AnyB)\312\264-%cosmos.f"
    "eegrant.v1beta1.FeeAllowanceIR\nallowance"
    "s:H\210\240\037\000\312\264-%cosmos.feegrant.v1beta1.FeeAl"
    "lowanceI\212\347\260*\026xion/MultiAnyAllowanceB)Z\'g"
    "ithub.com/burnt-labs/xion/x/xion/typesb\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_xion_2fv1_2ffeegrant_2eproto_deps[4] =
    {
        &::descriptor_table_amino_2famino_2eproto,
        &::descriptor_table_cosmos_5fproto_2fcosmos_2eproto,
        &::descriptor_table_gogoproto_2fgogo_2eproto,
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
};
static ::absl::once_flag descriptor_table_xion_2fv1_2ffeegrant_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xion_2fv1_2ffeegrant_2eproto = {
    false,
    false,
    886,
    descriptor_table_protodef_xion_2fv1_2ffeegrant_2eproto,
    "xion/v1/feegrant.proto",
    &descriptor_table_xion_2fv1_2ffeegrant_2eproto_once,
    descriptor_table_xion_2fv1_2ffeegrant_2eproto_deps,
    4,
    3,
    schemas,
    file_default_instances,
    TableStruct_xion_2fv1_2ffeegrant_2eproto::offsets,
    file_level_metadata_xion_2fv1_2ffeegrant_2eproto,
    file_level_enum_descriptors_xion_2fv1_2ffeegrant_2eproto,
    file_level_service_descriptors_xion_2fv1_2ffeegrant_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xion_2fv1_2ffeegrant_2eproto_getter() {
  return &descriptor_table_xion_2fv1_2ffeegrant_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xion_2fv1_2ffeegrant_2eproto(&descriptor_table_xion_2fv1_2ffeegrant_2eproto);
namespace xion {
namespace v1 {
// ===================================================================

class AuthzAllowance::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthzAllowance>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthzAllowance, _impl_._has_bits_);
  static const ::google::protobuf::Any& allowance(const AuthzAllowance* msg);
  static void set_has_allowance(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Any& AuthzAllowance::_Internal::allowance(const AuthzAllowance* msg) {
  return *msg->_impl_.allowance_;
}
void AuthzAllowance::clear_allowance() {
  if (_impl_.allowance_ != nullptr) _impl_.allowance_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
AuthzAllowance::AuthzAllowance(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xion.v1.AuthzAllowance)
}
AuthzAllowance::AuthzAllowance(const AuthzAllowance& from) : ::google::protobuf::Message() {
  AuthzAllowance* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.authz_grantee_){},
      decltype(_impl_.allowance_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.authz_grantee_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.authz_grantee_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_authz_grantee().empty()) {
    _this->_impl_.authz_grantee_.Set(from._internal_authz_grantee(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.allowance_ = new ::google::protobuf::Any(*from._impl_.allowance_);
  }

  // @@protoc_insertion_point(copy_constructor:xion.v1.AuthzAllowance)
}
inline void AuthzAllowance::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.authz_grantee_){},
      decltype(_impl_.allowance_){nullptr},
  };
  _impl_.authz_grantee_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.authz_grantee_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
AuthzAllowance::~AuthzAllowance() {
  // @@protoc_insertion_point(destructor:xion.v1.AuthzAllowance)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthzAllowance::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.authz_grantee_.Destroy();
  if (this != internal_default_instance()) delete _impl_.allowance_;
}
void AuthzAllowance::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void AuthzAllowance::Clear() {
// @@protoc_insertion_point(message_clear_start:xion.v1.AuthzAllowance)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.authz_grantee_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.allowance_ != nullptr);
    _impl_.allowance_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthzAllowance::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 44, 2> AuthzAllowance::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthzAllowance, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AuthzAllowance_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string authz_grantee = 2 [json_name = "authzGrantee", (.cosmos_proto.scalar) = "cosmos.AddressString"];
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AuthzAllowance, _impl_.authz_grantee_)}},
    // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AuthzAllowance, _impl_.allowance_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
    {PROTOBUF_FIELD_OFFSET(AuthzAllowance, _impl_.allowance_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string authz_grantee = 2 [json_name = "authzGrantee", (.cosmos_proto.scalar) = "cosmos.AddressString"];
    {PROTOBUF_FIELD_OFFSET(AuthzAllowance, _impl_.authz_grantee_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
    "\26\0\15\0\0\0\0\0"
    "xion.v1.AuthzAllowance"
    "authz_grantee"
  }},
};

::uint8_t* AuthzAllowance::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xion.v1.AuthzAllowance)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::allowance(this),
        _Internal::allowance(this).GetCachedSize(), target, stream);
  }

  // string authz_grantee = 2 [json_name = "authzGrantee", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_authz_grantee().empty()) {
    const std::string& _s = this->_internal_authz_grantee();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xion.v1.AuthzAllowance.authz_grantee");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xion.v1.AuthzAllowance)
  return target;
}

::size_t AuthzAllowance::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xion.v1.AuthzAllowance)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string authz_grantee = 2 [json_name = "authzGrantee", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_authz_grantee().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_authz_grantee());
  }

  // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.allowance_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthzAllowance::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    AuthzAllowance::MergeImpl
};
const ::google::protobuf::Message::ClassData*AuthzAllowance::GetClassData() const { return &_class_data_; }


void AuthzAllowance::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthzAllowance*>(&to_msg);
  auto& from = static_cast<const AuthzAllowance&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xion.v1.AuthzAllowance)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_authz_grantee().empty()) {
    _this->_internal_set_authz_grantee(from._internal_authz_grantee());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_allowance()->::google::protobuf::Any::MergeFrom(
        from._internal_allowance());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthzAllowance::CopyFrom(const AuthzAllowance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xion.v1.AuthzAllowance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthzAllowance::IsInitialized() const {
  return true;
}

void AuthzAllowance::InternalSwap(AuthzAllowance* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.authz_grantee_, lhs_arena,
                                       &other->_impl_.authz_grantee_, rhs_arena);
  swap(_impl_.allowance_, other->_impl_.allowance_);
}

::google::protobuf::Metadata AuthzAllowance::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xion_2fv1_2ffeegrant_2eproto_getter, &descriptor_table_xion_2fv1_2ffeegrant_2eproto_once,
      file_level_metadata_xion_2fv1_2ffeegrant_2eproto[0]);
}
// ===================================================================

class ContractsAllowance::_Internal {
 public:
  using HasBits = decltype(std::declval<ContractsAllowance>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ContractsAllowance, _impl_._has_bits_);
  static const ::google::protobuf::Any& allowance(const ContractsAllowance* msg);
  static void set_has_allowance(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Any& ContractsAllowance::_Internal::allowance(const ContractsAllowance* msg) {
  return *msg->_impl_.allowance_;
}
void ContractsAllowance::clear_allowance() {
  if (_impl_.allowance_ != nullptr) _impl_.allowance_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ContractsAllowance::ContractsAllowance(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xion.v1.ContractsAllowance)
}
ContractsAllowance::ContractsAllowance(const ContractsAllowance& from) : ::google::protobuf::Message() {
  ContractsAllowance* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.contract_addresses_){from._impl_.contract_addresses_},
      decltype(_impl_.allowance_){nullptr},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.allowance_ = new ::google::protobuf::Any(*from._impl_.allowance_);
  }

  // @@protoc_insertion_point(copy_constructor:xion.v1.ContractsAllowance)
}
inline void ContractsAllowance::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.contract_addresses_){arena},
      decltype(_impl_.allowance_){nullptr},
  };
}
ContractsAllowance::~ContractsAllowance() {
  // @@protoc_insertion_point(destructor:xion.v1.ContractsAllowance)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ContractsAllowance::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_contract_addresses()->~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.allowance_;
}
void ContractsAllowance::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void ContractsAllowance::Clear() {
// @@protoc_insertion_point(message_clear_start:xion.v1.ContractsAllowance)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_contract_addresses()->Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.allowance_ != nullptr);
    _impl_.allowance_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ContractsAllowance::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 53, 2> ContractsAllowance::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ContractsAllowance, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ContractsAllowance_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated string contract_addresses = 2 [json_name = "contractAddresses", (.cosmos_proto.scalar) = "cosmos.AddressString"];
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ContractsAllowance, _impl_.contract_addresses_)}},
    // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ContractsAllowance, _impl_.allowance_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
    {PROTOBUF_FIELD_OFFSET(ContractsAllowance, _impl_.allowance_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated string contract_addresses = 2 [json_name = "contractAddresses", (.cosmos_proto.scalar) = "cosmos.AddressString"];
    {PROTOBUF_FIELD_OFFSET(ContractsAllowance, _impl_.contract_addresses_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
    "\32\0\22\0\0\0\0\0"
    "xion.v1.ContractsAllowance"
    "contract_addresses"
  }},
};

::uint8_t* ContractsAllowance::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xion.v1.ContractsAllowance)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::allowance(this),
        _Internal::allowance(this).GetCachedSize(), target, stream);
  }

  // repeated string contract_addresses = 2 [json_name = "contractAddresses", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  for (int i = 0, n = this->_internal_contract_addresses_size(); i < n; ++i) {
    const auto& s = this->_internal_contract_addresses().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xion.v1.ContractsAllowance.contract_addresses");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xion.v1.ContractsAllowance)
  return target;
}

::size_t ContractsAllowance::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xion.v1.ContractsAllowance)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string contract_addresses = 2 [json_name = "contractAddresses", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_contract_addresses().size());
  for (int i = 0, n = _internal_contract_addresses().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_contract_addresses().Get(i));
  }
  // .google.protobuf.Any allowance = 1 [json_name = "allowance", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.allowance_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ContractsAllowance::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    ContractsAllowance::MergeImpl
};
const ::google::protobuf::Message::ClassData*ContractsAllowance::GetClassData() const { return &_class_data_; }


void ContractsAllowance::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ContractsAllowance*>(&to_msg);
  auto& from = static_cast<const ContractsAllowance&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xion.v1.ContractsAllowance)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_contract_addresses()->MergeFrom(from._internal_contract_addresses());
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_allowance()->::google::protobuf::Any::MergeFrom(
        from._internal_allowance());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ContractsAllowance::CopyFrom(const ContractsAllowance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xion.v1.ContractsAllowance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ContractsAllowance::IsInitialized() const {
  return true;
}

void ContractsAllowance::InternalSwap(ContractsAllowance* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.contract_addresses_.InternalSwap(&other->_impl_.contract_addresses_);
  swap(_impl_.allowance_, other->_impl_.allowance_);
}

::google::protobuf::Metadata ContractsAllowance::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xion_2fv1_2ffeegrant_2eproto_getter, &descriptor_table_xion_2fv1_2ffeegrant_2eproto_once,
      file_level_metadata_xion_2fv1_2ffeegrant_2eproto[1]);
}
// ===================================================================

class MultiAnyAllowance::_Internal {
 public:
};

void MultiAnyAllowance::clear_allowances() {
  _internal_mutable_allowances()->Clear();
}
MultiAnyAllowance::MultiAnyAllowance(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xion.v1.MultiAnyAllowance)
}
MultiAnyAllowance::MultiAnyAllowance(const MultiAnyAllowance& from) : ::google::protobuf::Message() {
  MultiAnyAllowance* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.allowances_){from._impl_.allowances_},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:xion.v1.MultiAnyAllowance)
}
inline void MultiAnyAllowance::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.allowances_){arena},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
MultiAnyAllowance::~MultiAnyAllowance() {
  // @@protoc_insertion_point(destructor:xion.v1.MultiAnyAllowance)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MultiAnyAllowance::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.allowances_.~RepeatedPtrField();
}
void MultiAnyAllowance::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void MultiAnyAllowance::Clear() {
// @@protoc_insertion_point(message_clear_start:xion.v1.MultiAnyAllowance)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_allowances()->Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MultiAnyAllowance::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> MultiAnyAllowance::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MultiAnyAllowance_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .google.protobuf.Any allowances = 1 [json_name = "allowances", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MultiAnyAllowance, _impl_.allowances_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .google.protobuf.Any allowances = 1 [json_name = "allowances", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
    {PROTOBUF_FIELD_OFFSET(MultiAnyAllowance, _impl_.allowances_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
  }},
};

::uint8_t* MultiAnyAllowance::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xion.v1.MultiAnyAllowance)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .google.protobuf.Any allowances = 1 [json_name = "allowances", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_allowances_size()); i < n; i++) {
    const auto& repfield = this->_internal_allowances().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xion.v1.MultiAnyAllowance)
  return target;
}

::size_t MultiAnyAllowance::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xion.v1.MultiAnyAllowance)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .google.protobuf.Any allowances = 1 [json_name = "allowances", (.cosmos_proto.accepts_interface) = "cosmos.feegrant.v1beta1.FeeAllowanceI"];
  total_size += 1UL * this->_internal_allowances_size();
  for (const auto& msg : this->_internal_allowances()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MultiAnyAllowance::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    MultiAnyAllowance::MergeImpl
};
const ::google::protobuf::Message::ClassData*MultiAnyAllowance::GetClassData() const { return &_class_data_; }


void MultiAnyAllowance::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MultiAnyAllowance*>(&to_msg);
  auto& from = static_cast<const MultiAnyAllowance&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xion.v1.MultiAnyAllowance)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_allowances()->MergeFrom(from._internal_allowances());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MultiAnyAllowance::CopyFrom(const MultiAnyAllowance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xion.v1.MultiAnyAllowance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MultiAnyAllowance::IsInitialized() const {
  return true;
}

void MultiAnyAllowance::InternalSwap(MultiAnyAllowance* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.allowances_.InternalSwap(&other->_impl_.allowances_);
}

::google::protobuf::Metadata MultiAnyAllowance::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xion_2fv1_2ffeegrant_2eproto_getter, &descriptor_table_xion_2fv1_2ffeegrant_2eproto_once,
      file_level_metadata_xion_2fv1_2ffeegrant_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace xion
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
