// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package cosmwasm.wasm.v1.proposal_legacy

/** Deprecated: Do not use. Since wasmd v0.40, there is no longer a need for
  * an explicit UpdateInstantiateConfigProposal. To update instantiate config
  * to a set of code ids, a simple MsgUpdateInstantiateConfig can be invoked from
  * the x/gov module via a v1 governance proposal.
  *
  * @param title
  *   Title is a short summary
  * @param description
  *   Description is a human readable text
  * @param accessConfigUpdates
  *   AccessConfigUpdates contains the list of code ids and the access config
  *   to be applied.
  */
@SerialVersionUID(0L)
@scala.deprecated(message="Marked as deprecated in proto file", "")
final case class UpdateInstantiateConfigProposal(
    title: _root_.scala.Predef.String = "",
    description: _root_.scala.Predef.String = "",
    accessConfigUpdates: _root_.scala.Seq[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[UpdateInstantiateConfigProposal] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = title
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = description
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      accessConfigUpdates.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = title
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = description
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      accessConfigUpdates.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withTitle(__v: _root_.scala.Predef.String): UpdateInstantiateConfigProposal = copy(title = __v)
    def withDescription(__v: _root_.scala.Predef.String): UpdateInstantiateConfigProposal = copy(description = __v)
    def clearAccessConfigUpdates = copy(accessConfigUpdates = _root_.scala.Seq.empty)
    def addAccessConfigUpdates(__vs: cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate *): UpdateInstantiateConfigProposal = addAllAccessConfigUpdates(__vs)
    def addAllAccessConfigUpdates(__vs: Iterable[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate]): UpdateInstantiateConfigProposal = copy(accessConfigUpdates = accessConfigUpdates ++ __vs)
    def withAccessConfigUpdates(__v: _root_.scala.Seq[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate]): UpdateInstantiateConfigProposal = copy(accessConfigUpdates = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = title
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = description
          if (__t != "") __t else null
        }
        case 3 => accessConfigUpdates
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(title)
        case 2 => _root_.scalapb.descriptors.PString(description)
        case 3 => _root_.scalapb.descriptors.PRepeated(accessConfigUpdates.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal.type = cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal
    // @@protoc_insertion_point(GeneratedMessage[cosmwasm.wasm.v1.UpdateInstantiateConfigProposal])
}

@scala.deprecated(message="Marked as deprecated in proto file", "")
object UpdateInstantiateConfigProposal extends scalapb.GeneratedMessageCompanion[cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal = {
    var __title: _root_.scala.Predef.String = ""
    var __description: _root_.scala.Predef.String = ""
    val __accessConfigUpdates: _root_.scala.collection.immutable.VectorBuilder[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate] = new _root_.scala.collection.immutable.VectorBuilder[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __title = _input__.readStringRequireUtf8()
        case 18 =>
          __description = _input__.readStringRequireUtf8()
        case 26 =>
          __accessConfigUpdates += _root_.scalapb.LiteParser.readMessage[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal(
        title = __title,
        description = __description,
        accessConfigUpdates = __accessConfigUpdates.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal(
        title = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        description = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        accessConfigUpdates = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = cosmwasm.wasm.v1.proposal_legacy.ProposalLegacyProto.javaDescriptor.getMessageTypes().get(11)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = cosmwasm.wasm.v1.proposal_legacy.ProposalLegacyProto.scalaDescriptor.messages(11)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal(
    title = "",
    description = "",
    accessConfigUpdates = _root_.scala.Seq.empty
  )
  implicit class UpdateInstantiateConfigProposalLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal](_l) {
    def title: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.title)((c_, f_) => c_.copy(title = f_))
    def description: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.description)((c_, f_) => c_.copy(description = f_))
    def accessConfigUpdates: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate]] = field(_.accessConfigUpdates)((c_, f_) => c_.copy(accessConfigUpdates = f_))
  }
  final val TITLE_FIELD_NUMBER = 1
  final val DESCRIPTION_FIELD_NUMBER = 2
  final val ACCESS_CONFIG_UPDATES_FIELD_NUMBER = 3
  def of(
    title: _root_.scala.Predef.String,
    description: _root_.scala.Predef.String,
    accessConfigUpdates: _root_.scala.Seq[cosmwasm.wasm.v1.proposal_legacy.AccessConfigUpdate]
  ): _root_.cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal = _root_.cosmwasm.wasm.v1.proposal_legacy.UpdateInstantiateConfigProposal(
    title,
    description,
    accessConfigUpdates
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[cosmwasm.wasm.v1.UpdateInstantiateConfigProposal])
}
