// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tendermint/types/types.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tendermint.types;

@kotlin.jvm.JvmName("-initializeextendedCommitSig")
public inline fun extendedCommitSig(block: tendermint.types.ExtendedCommitSigKt.Dsl.() -> kotlin.Unit): tendermint.types.Types.ExtendedCommitSig =
  tendermint.types.ExtendedCommitSigKt.Dsl._create(tendermint.types.Types.ExtendedCommitSig.newBuilder()).apply { block() }._build()
/**
 * ```
 * ExtendedCommitSig retains all the same fields as CommitSig but adds vote
 * extension-related fields. We use two signatures to ensure backwards compatibility.
 * That is the digest of the original signature is still the same in prior versions
 * ```
 *
 * Protobuf type `tendermint.types.ExtendedCommitSig`
 */
public object ExtendedCommitSigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tendermint.types.Types.ExtendedCommitSig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tendermint.types.Types.ExtendedCommitSig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tendermint.types.Types.ExtendedCommitSig = _builder.build()

    /**
     * `.tendermint.types.BlockIDFlag block_id_flag = 1 [json_name = "blockIdFlag"];`
     */
    public var blockIdFlag: tendermint.types.ValidatorOuterClass.BlockIDFlag
      @kotlin.jvm.JvmName("getBlockIdFlag")
        get() = _builder.blockIdFlag
      @kotlin.jvm.JvmName("setBlockIdFlag")
        set(value) {
        _builder.blockIdFlag = value
      }
    public var blockIdFlagValue: kotlin.Int
      @kotlin.jvm.JvmName("getBlockIdFlagValue")
        get() = _builder.blockIdFlagValue
      @kotlin.jvm.JvmName("setBlockIdFlagValue")
        set(value) {
        _builder.blockIdFlagValue = value
      }
    /**
     * `.tendermint.types.BlockIDFlag block_id_flag = 1 [json_name = "blockIdFlag"];`
     */
    public fun clearBlockIdFlag() {
      _builder.clearBlockIdFlag()
    }

    /**
     * `bytes validator_address = 2 [json_name = "validatorAddress"];`
     */
    public var validatorAddress: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getValidatorAddress")
        get() = _builder.validatorAddress
      @kotlin.jvm.JvmName("setValidatorAddress")
        set(value) {
        _builder.validatorAddress = value
      }
    /**
     * `bytes validator_address = 2 [json_name = "validatorAddress"];`
     */
    public fun clearValidatorAddress() {
      _builder.clearValidatorAddress()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3 [json_name = "timestamp", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ExtendedCommitSigKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * `bytes signature = 4 [json_name = "signature"];`
     */
    public var signature: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSignature")
        get() = _builder.signature
      @kotlin.jvm.JvmName("setSignature")
        set(value) {
        _builder.signature = value
      }
    /**
     * `bytes signature = 4 [json_name = "signature"];`
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }

    /**
     * ```
     * Vote extension data
     * ```
     *
     * `bytes extension = 5 [json_name = "extension"];`
     */
    public var extension: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getExtension")
        get() = _builder.extension
      @kotlin.jvm.JvmName("setExtension")
        set(value) {
        _builder.extension = value
      }
    /**
     * ```
     * Vote extension data
     * ```
     *
     * `bytes extension = 5 [json_name = "extension"];`
     */
    public fun clearExtension() {
      _builder.clearExtension()
    }

    /**
     * ```
     * Vote extension signature
     * ```
     *
     * `bytes extension_signature = 6 [json_name = "extensionSignature"];`
     */
    public var extensionSignature: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getExtensionSignature")
        get() = _builder.extensionSignature
      @kotlin.jvm.JvmName("setExtensionSignature")
        set(value) {
        _builder.extensionSignature = value
      }
    /**
     * ```
     * Vote extension signature
     * ```
     *
     * `bytes extension_signature = 6 [json_name = "extensionSignature"];`
     */
    public fun clearExtensionSignature() {
      _builder.clearExtensionSignature()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun tendermint.types.Types.ExtendedCommitSig.copy(block: `tendermint.types`.ExtendedCommitSigKt.Dsl.() -> kotlin.Unit): tendermint.types.Types.ExtendedCommitSig =
  `tendermint.types`.ExtendedCommitSigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val tendermint.types.Types.ExtendedCommitSigOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

