// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package ibc.core.client.v1

/** ClientConsensusStates defines all the stored consensus states for a given
  * client.
  *
  * @param clientId
  *   client identifier
  * @param consensusStates
  *   consensus states and their heights associated with the client
  */
@SerialVersionUID(0L)
final case class ClientConsensusStates(
    clientId: _root_.scala.Predef.String = "",
    consensusStates: _root_.scala.Seq[ibc.core.client.v1.ConsensusStateWithHeight] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ClientConsensusStates] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = clientId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      consensusStates.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = clientId
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      consensusStates.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withClientId(__v: _root_.scala.Predef.String): ClientConsensusStates = copy(clientId = __v)
    def clearConsensusStates = copy(consensusStates = _root_.scala.Seq.empty)
    def addConsensusStates(__vs: ibc.core.client.v1.ConsensusStateWithHeight *): ClientConsensusStates = addAllConsensusStates(__vs)
    def addAllConsensusStates(__vs: Iterable[ibc.core.client.v1.ConsensusStateWithHeight]): ClientConsensusStates = copy(consensusStates = consensusStates ++ __vs)
    def withConsensusStates(__v: _root_.scala.Seq[ibc.core.client.v1.ConsensusStateWithHeight]): ClientConsensusStates = copy(consensusStates = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = clientId
          if (__t != "") __t else null
        }
        case 2 => consensusStates
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(clientId)
        case 2 => _root_.scalapb.descriptors.PRepeated(consensusStates.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: ibc.core.client.v1.ClientConsensusStates.type = ibc.core.client.v1.ClientConsensusStates
    // @@protoc_insertion_point(GeneratedMessage[ibc.core.client.v1.ClientConsensusStates])
}

object ClientConsensusStates extends scalapb.GeneratedMessageCompanion[ibc.core.client.v1.ClientConsensusStates] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[ibc.core.client.v1.ClientConsensusStates] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): ibc.core.client.v1.ClientConsensusStates = {
    var __clientId: _root_.scala.Predef.String = ""
    val __consensusStates: _root_.scala.collection.immutable.VectorBuilder[ibc.core.client.v1.ConsensusStateWithHeight] = new _root_.scala.collection.immutable.VectorBuilder[ibc.core.client.v1.ConsensusStateWithHeight]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __clientId = _input__.readStringRequireUtf8()
        case 18 =>
          __consensusStates += _root_.scalapb.LiteParser.readMessage[ibc.core.client.v1.ConsensusStateWithHeight](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    ibc.core.client.v1.ClientConsensusStates(
        clientId = __clientId,
        consensusStates = __consensusStates.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[ibc.core.client.v1.ClientConsensusStates] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      ibc.core.client.v1.ClientConsensusStates(
        clientId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        consensusStates = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[ibc.core.client.v1.ConsensusStateWithHeight]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ibc.core.client.v1.ClientProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ibc.core.client.v1.ClientProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = ibc.core.client.v1.ConsensusStateWithHeight
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = ibc.core.client.v1.ClientConsensusStates(
    clientId = "",
    consensusStates = _root_.scala.Seq.empty
  )
  implicit class ClientConsensusStatesLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, ibc.core.client.v1.ClientConsensusStates]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, ibc.core.client.v1.ClientConsensusStates](_l) {
    def clientId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.clientId)((c_, f_) => c_.copy(clientId = f_))
    def consensusStates: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[ibc.core.client.v1.ConsensusStateWithHeight]] = field(_.consensusStates)((c_, f_) => c_.copy(consensusStates = f_))
  }
  final val CLIENT_ID_FIELD_NUMBER = 1
  final val CONSENSUS_STATES_FIELD_NUMBER = 2
  def of(
    clientId: _root_.scala.Predef.String,
    consensusStates: _root_.scala.Seq[ibc.core.client.v1.ConsensusStateWithHeight]
  ): _root_.ibc.core.client.v1.ClientConsensusStates = _root_.ibc.core.client.v1.ClientConsensusStates(
    clientId,
    consensusStates
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[ibc.core.client.v1.ClientConsensusStates])
}
