// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package ibc.core.client.v1

object TxProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    amino.AminoProto,
    cosmos.msg.v1.MsgProto,
    cosmos.upgrade.v1beta1.UpgradeProto,
    com.google.protobuf.GogoProto,
    com.google.protobuf.any.AnyProto,
    ibc.core.client.v1.ClientProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      ibc.core.client.v1.MsgCreateClient,
      ibc.core.client.v1.MsgCreateClientResponse,
      ibc.core.client.v1.MsgUpdateClient,
      ibc.core.client.v1.MsgUpdateClientResponse,
      ibc.core.client.v1.MsgUpgradeClient,
      ibc.core.client.v1.MsgUpgradeClientResponse,
      ibc.core.client.v1.MsgSubmitMisbehaviour,
      ibc.core.client.v1.MsgSubmitMisbehaviourResponse,
      ibc.core.client.v1.MsgRecoverClient,
      ibc.core.client.v1.MsgRecoverClientResponse,
      ibc.core.client.v1.MsgIBCSoftwareUpgrade,
      ibc.core.client.v1.MsgIBCSoftwareUpgradeResponse,
      ibc.core.client.v1.MsgUpdateParams,
      ibc.core.client.v1.MsgUpdateParamsResponse,
      ibc.core.client.v1.MsgDeleteClientCreator,
      ibc.core.client.v1.MsgDeleteClientCreatorResponse
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChtpYmMvY29yZS9jbGllbnQvdjEvdHgucHJvdG8SEmliYy5jb3JlLmNsaWVudC52MRoRYW1pbm8vYW1pbm8ucHJvdG8aF2Nvc
  21vcy9tc2cvdjEvbXNnLnByb3RvGiRjb3Ntb3MvdXBncmFkZS92MWJldGExL3VwZ3JhZGUucHJvdG8aFGdvZ29wcm90by9nb2dvL
  nByb3RvGhlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvGh9pYmMvY29yZS9jbGllbnQvdjEvY2xpZW50LnByb3RvIuYBCg9Nc2dDc
  mVhdGVDbGllbnQSSQoMY2xpZW50X3N0YXRlGAEgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIQ4j8NEgtjbGllbnRTdGF0ZVILY
  2xpZW50U3RhdGUSUgoPY29uc2Vuc3VzX3N0YXRlGAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUIT4j8QEg5jb25zZW5zdXNTd
  GF0ZVIOY29uc2Vuc3VzU3RhdGUSIwoGc2lnbmVyGAMgASgJQgviPwgSBnNpZ25lclIGc2lnbmVyOg+IoB8AguewKgZzaWduZXIiS
  woXTXNnQ3JlYXRlQ2xpZW50UmVzcG9uc2USKgoJY2xpZW50X2lkGAEgASgJQg3iPwoSCGNsaWVudElkUghjbGllbnRJZDoEiKAfA
  CLEAQoPTXNnVXBkYXRlQ2xpZW50EioKCWNsaWVudF9pZBgBIAEoCUIN4j8KEghjbGllbnRJZFIIY2xpZW50SWQSTwoOY2xpZW50X
  21lc3NhZ2UYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QhLiPw8SDWNsaWVudE1lc3NhZ2VSDWNsaWVudE1lc3NhZ2USIwoGc
  2lnbmVyGAMgASgJQgviPwgSBnNpZ25lclIGc2lnbmVyOg+IoB8AguewKgZzaWduZXIiGQoXTXNnVXBkYXRlQ2xpZW50UmVzcG9uc
  2UiwgMKEE1zZ1VwZ3JhZGVDbGllbnQSKgoJY2xpZW50X2lkGAEgASgJQg3iPwoSCGNsaWVudElkUghjbGllbnRJZBJJCgxjbGllb
  nRfc3RhdGUYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QhDiPw0SC2NsaWVudFN0YXRlUgtjbGllbnRTdGF0ZRJSCg9jb25zZ
  W5zdXNfc3RhdGUYAyABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QhPiPxASDmNvbnNlbnN1c1N0YXRlUg5jb25zZW5zdXNTdGF0Z
  RJJChRwcm9vZl91cGdyYWRlX2NsaWVudBgEIAEoDEIX4j8UEhJwcm9vZlVwZ3JhZGVDbGllbnRSEnByb29mVXBncmFkZUNsaWVud
  BJiCh1wcm9vZl91cGdyYWRlX2NvbnNlbnN1c19zdGF0ZRgFIAEoDEIf4j8cEhpwcm9vZlVwZ3JhZGVDb25zZW5zdXNTdGF0ZVIac
  HJvb2ZVcGdyYWRlQ29uc2Vuc3VzU3RhdGUSIwoGc2lnbmVyGAYgASgJQgviPwgSBnNpZ25lclIGc2lnbmVyOg+IoB8AguewKgZza
  WduZXIiGgoYTXNnVXBncmFkZUNsaWVudFJlc3BvbnNlIsgBChVNc2dTdWJtaXRNaXNiZWhhdmlvdXISKgoJY2xpZW50X2lkGAEgA
  SgJQg3iPwoSCGNsaWVudElkUghjbGllbnRJZBJLCgxtaXNiZWhhdmlvdXIYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QhHiP
  w4SDG1pc2JlaGF2aW91clIMbWlzYmVoYXZpb3VyEiMKBnNpZ25lchgDIAEoCUIL4j8IEgZzaWduZXJSBnNpZ25lcjoRGAGIoB8Ag
  uewKgZzaWduZXIiHwodTXNnU3VibWl0TWlzYmVoYXZpb3VyUmVzcG9uc2Ui9QEKEE1zZ1JlY292ZXJDbGllbnQSQAoRc3ViamVjd
  F9jbGllbnRfaWQYASABKAlCFOI/ERIPc3ViamVjdENsaWVudElkUg9zdWJqZWN0Q2xpZW50SWQSSQoUc3Vic3RpdHV0ZV9jbGllb
  nRfaWQYAiABKAlCF+I/FBISc3Vic3RpdHV0ZUNsaWVudElkUhJzdWJzdGl0dXRlQ2xpZW50SWQSIwoGc2lnbmVyGAMgASgJQgviP
  wgSBnNpZ25lclIGc2lnbmVyOi+IoB8AguewKgZzaWduZXKK57AqG2Nvc21vcy1zZGsvTXNnUmVjb3ZlckNsaWVudCIaChhNc2dSZ
  WNvdmVyQ2xpZW50UmVzcG9uc2Ui7gEKFU1zZ0lCQ1NvZnR3YXJlVXBncmFkZRI/CgRwbGFuGAEgASgLMhwuY29zbW9zLnVwZ3JhZ
  GUudjFiZXRhMS5QbGFuQg3iPwYSBHBsYW7I3h8AUgRwbGFuEmIKFXVwZ3JhZGVkX2NsaWVudF9zdGF0ZRgCIAEoCzIULmdvb2dsZ
  S5wcm90b2J1Zi5BbnlCGOI/FRITdXBncmFkZWRDbGllbnRTdGF0ZVITdXBncmFkZWRDbGllbnRTdGF0ZRIjCgZzaWduZXIYAyABK
  AlCC+I/CBIGc2lnbmVyUgZzaWduZXI6C4LnsCoGc2lnbmVyIh8KHU1zZ0lCQ1NvZnR3YXJlVXBncmFkZVJlc3BvbnNlIowBCg9Nc
  2dVcGRhdGVQYXJhbXMSIwoGc2lnbmVyGAEgASgJQgviPwgSBnNpZ25lclIGc2lnbmVyEkMKBnBhcmFtcxgCIAEoCzIaLmliYy5jb
  3JlLmNsaWVudC52MS5QYXJhbXNCD+I/CBIGcGFyYW1zyN4fAFIGcGFyYW1zOg+IoB8AguewKgZzaWduZXIiGQoXTXNnVXBkYXRlU
  GFyYW1zUmVzcG9uc2UiegoWTXNnRGVsZXRlQ2xpZW50Q3JlYXRvchIqCgljbGllbnRfaWQYASABKAlCDeI/ChIIY2xpZW50SWRSC
  GNsaWVudElkEiMKBnNpZ25lchgCIAEoCUIL4j8IEgZzaWduZXJSBnNpZ25lcjoPiKAfAILnsCoGc2lnbmVyIiAKHk1zZ0RlbGV0Z
  UNsaWVudENyZWF0b3JSZXNwb25zZTLhBgoDTXNnEmAKDENyZWF0ZUNsaWVudBIjLmliYy5jb3JlLmNsaWVudC52MS5Nc2dDcmVhd
  GVDbGllbnQaKy5pYmMuY29yZS5jbGllbnQudjEuTXNnQ3JlYXRlQ2xpZW50UmVzcG9uc2USYAoMVXBkYXRlQ2xpZW50EiMuaWJjL
  mNvcmUuY2xpZW50LnYxLk1zZ1VwZGF0ZUNsaWVudBorLmliYy5jb3JlLmNsaWVudC52MS5Nc2dVcGRhdGVDbGllbnRSZXNwb25zZ
  RJjCg1VcGdyYWRlQ2xpZW50EiQuaWJjLmNvcmUuY2xpZW50LnYxLk1zZ1VwZ3JhZGVDbGllbnQaLC5pYmMuY29yZS5jbGllbnQud
  jEuTXNnVXBncmFkZUNsaWVudFJlc3BvbnNlEnIKElN1Ym1pdE1pc2JlaGF2aW91chIpLmliYy5jb3JlLmNsaWVudC52MS5Nc2dTd
  WJtaXRNaXNiZWhhdmlvdXIaMS5pYmMuY29yZS5jbGllbnQudjEuTXNnU3VibWl0TWlzYmVoYXZpb3VyUmVzcG9uc2USYwoNUmVjb
  3ZlckNsaWVudBIkLmliYy5jb3JlLmNsaWVudC52MS5Nc2dSZWNvdmVyQ2xpZW50GiwuaWJjLmNvcmUuY2xpZW50LnYxLk1zZ1JlY
  292ZXJDbGllbnRSZXNwb25zZRJyChJJQkNTb2Z0d2FyZVVwZ3JhZGUSKS5pYmMuY29yZS5jbGllbnQudjEuTXNnSUJDU29mdHdhc
  mVVcGdyYWRlGjEuaWJjLmNvcmUuY2xpZW50LnYxLk1zZ0lCQ1NvZnR3YXJlVXBncmFkZVJlc3BvbnNlEmYKElVwZGF0ZUNsaWVud
  FBhcmFtcxIjLmliYy5jb3JlLmNsaWVudC52MS5Nc2dVcGRhdGVQYXJhbXMaKy5pYmMuY29yZS5jbGllbnQudjEuTXNnVXBkYXRlU
  GFyYW1zUmVzcG9uc2USdQoTRGVsZXRlQ2xpZW50Q3JlYXRvchIqLmliYy5jb3JlLmNsaWVudC52MS5Nc2dEZWxldGVDbGllbnRDc
  mVhdG9yGjIuaWJjLmNvcmUuY2xpZW50LnYxLk1zZ0RlbGV0ZUNsaWVudENyZWF0b3JSZXNwb25zZRoFgOewKgFCO1o5Z2l0aHViL
  mNvbS9jb3Ntb3MvaWJjLWdvL3YxMC9tb2R1bGVzL2NvcmUvMDItY2xpZW50L3R5cGVzYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      amino.AminoProto.javaDescriptor,
      cosmos.msg.v1.MsgProto.javaDescriptor,
      cosmos.upgrade.v1beta1.UpgradeProto.javaDescriptor,
      com.google.protobuf.GogoProto.javaDescriptor,
      com.google.protobuf.any.AnyProto.javaDescriptor,
      ibc.core.client.v1.ClientProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}