# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/auth/module/v1/module.proto

require 'google/protobuf'

require 'cosmos/app/v1alpha1/module_pb'


descriptor_data = "\n\"cosmos/auth/module/v1/module.proto\x12\x15\x63osmos.auth.module.v1\x1a cosmos/app/v1alpha1/module.proto\"\xaa\x02\n\x06Module\x12#\n\rbech32_prefix\x18\x01 \x01(\tR\x0c\x62\x65\x63h32Prefix\x12l\n\x1amodule_account_permissions\x18\x02 \x03(\x0b\x32..cosmos.auth.module.v1.ModuleAccountPermissionR\x18moduleAccountPermissions\x12\x1c\n\tauthority\x18\x03 \x01(\tR\tauthority\x12\x42\n\x1d\x65nable_unordered_transactions\x18\x04 \x01(\x08R\x1b\x65nableUnorderedTransactions:+\xba\xc0\x96\xda\x01%\n#github.com/cosmos/cosmos-sdk/x/auth\"U\n\x17ModuleAccountPermission\x12\x18\n\x07\x61\x63\x63ount\x18\x01 \x01(\tR\x07\x61\x63\x63ount\x12 \n\x0bpermissions\x18\x02 \x03(\tR\x0bpermissionsb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Cosmos
  module Auth
    module Module
      module V1
        Module = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.auth.module.v1.Module").msgclass
        ModuleAccountPermission = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cosmos.auth.module.v1.ModuleAccountPermission").msgclass
      end
    end
  end
end
