// @generated
// This file is @generated by prost-build.
/// Params defines the parameters for the module.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Params {
    /// in nanoseconds
    #[prost(uint64, tag="1")]
    pub time_offset: u64,
    /// gas to deploy a new project/audience
    #[prost(uint64, tag="2")]
    pub deployment_gas: u64,
}
// @@protoc_insertion_point(module)
