<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xion/zk/v1/query.proto

namespace Xion\Zk\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ProofVerifyResponse defines the response structure for proof verification.
 *
 * Generated from protobuf message <code>xion.zk.v1.ProofVerifyResponse</code>
 */
class ProofVerifyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * verified indicates whether the proof verification was successful.
     *
     * Generated from protobuf field <code>bool verified = 1 [json_name = "verified"];</code>
     */
    protected $verified = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $verified
     *           verified indicates whether the proof verification was successful.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xion\Zk\V1\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * verified indicates whether the proof verification was successful.
     *
     * Generated from protobuf field <code>bool verified = 1 [json_name = "verified"];</code>
     * @return bool
     */
    public function getVerified()
    {
        return $this->verified;
    }

    /**
     * verified indicates whether the proof verification was successful.
     *
     * Generated from protobuf field <code>bool verified = 1 [json_name = "verified"];</code>
     * @param bool $var
     * @return $this
     */
    public function setVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->verified = $var;

        return $this;
    }

}

