// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: xion/feeabs/v1beta1/osmosisibc.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package xion.feeabs.v1beta1;

@kotlin.jvm.JvmName("-initializeinterchainQueryPacketData")
public inline fun interchainQueryPacketData(block: xion.feeabs.v1beta1.InterchainQueryPacketDataKt.Dsl.() -> kotlin.Unit): xion.feeabs.v1beta1.Osmosisibc.InterchainQueryPacketData =
  xion.feeabs.v1beta1.InterchainQueryPacketDataKt.Dsl._create(xion.feeabs.v1beta1.Osmosisibc.InterchainQueryPacketData.newBuilder()).apply { block() }._build()
/**
 * ```
 * InterchainQueryPacketData is comprised of raw query.
 * ```
 *
 * Protobuf type `xion.feeabs.v1beta1.InterchainQueryPacketData`
 */
public object InterchainQueryPacketDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: xion.feeabs.v1beta1.Osmosisibc.InterchainQueryPacketData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: xion.feeabs.v1beta1.Osmosisibc.InterchainQueryPacketData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): xion.feeabs.v1beta1.Osmosisibc.InterchainQueryPacketData = _builder.build()

    /**
     * ```
     * data defines the raw query data
     * ```
     *
     * `bytes data = 1 [json_name = "data"];`
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * ```
     * data defines the raw query data
     * ```
     *
     * `bytes data = 1 [json_name = "data"];`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * ```
     * optional memo
     * ```
     *
     * `string memo = 2 [json_name = "memo"];`
     */
    public var memo: kotlin.String
      @JvmName("getMemo")
      get() = _builder.getMemo()
      @JvmName("setMemo")
      set(value) {
        _builder.setMemo(value)
      }
    /**
     * ```
     * optional memo
     * ```
     *
     * `string memo = 2 [json_name = "memo"];`
     */
    public fun clearMemo() {
      _builder.clearMemo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun xion.feeabs.v1beta1.Osmosisibc.InterchainQueryPacketData.copy(block: xion.feeabs.v1beta1.InterchainQueryPacketDataKt.Dsl.() -> kotlin.Unit): xion.feeabs.v1beta1.Osmosisibc.InterchainQueryPacketData =
  xion.feeabs.v1beta1.InterchainQueryPacketDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

