// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ibc/applications/transfer/v1/query.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ibc.applications.transfer.v1;

@kotlin.jvm.JvmName("-initializequeryDenomsResponse")
public inline fun queryDenomsResponse(block: ibc.applications.transfer.v1.QueryDenomsResponseKt.Dsl.() -> kotlin.Unit): ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponse =
  ibc.applications.transfer.v1.QueryDenomsResponseKt.Dsl._create(ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * QueryDenomsResponse is the response type for the Query/Denoms RPC
 * method.
 * ```
 *
 * Protobuf type `ibc.applications.transfer.v1.QueryDenomsResponse`
 */
public object QueryDenomsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DenomsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * denoms returns all denominations.
     * ```
     *
     * `repeated .ibc.applications.transfer.v1.Denom denoms = 1 [json_name = "denoms", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Denoms"];`
     */
     public val denoms: com.google.protobuf.kotlin.DslList<ibc.applications.transfer.v1.TokenOuterClass.Denom, DenomsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.denomsList
      )
    /**
     * ```
     * denoms returns all denominations.
     * ```
     *
     * `repeated .ibc.applications.transfer.v1.Denom denoms = 1 [json_name = "denoms", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Denoms"];`
     * @param value The denoms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDenoms")
    public fun com.google.protobuf.kotlin.DslList<ibc.applications.transfer.v1.TokenOuterClass.Denom, DenomsProxy>.add(value: ibc.applications.transfer.v1.TokenOuterClass.Denom) {
      _builder.addDenoms(value)
    }
    /**
     * ```
     * denoms returns all denominations.
     * ```
     *
     * `repeated .ibc.applications.transfer.v1.Denom denoms = 1 [json_name = "denoms", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Denoms"];`
     * @param value The denoms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDenoms")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ibc.applications.transfer.v1.TokenOuterClass.Denom, DenomsProxy>.plusAssign(value: ibc.applications.transfer.v1.TokenOuterClass.Denom) {
      add(value)
    }
    /**
     * ```
     * denoms returns all denominations.
     * ```
     *
     * `repeated .ibc.applications.transfer.v1.Denom denoms = 1 [json_name = "denoms", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Denoms"];`
     * @param values The denoms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDenoms")
    public fun com.google.protobuf.kotlin.DslList<ibc.applications.transfer.v1.TokenOuterClass.Denom, DenomsProxy>.addAll(values: kotlin.collections.Iterable<ibc.applications.transfer.v1.TokenOuterClass.Denom>) {
      _builder.addAllDenoms(values)
    }
    /**
     * ```
     * denoms returns all denominations.
     * ```
     *
     * `repeated .ibc.applications.transfer.v1.Denom denoms = 1 [json_name = "denoms", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Denoms"];`
     * @param values The denoms to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDenoms")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ibc.applications.transfer.v1.TokenOuterClass.Denom, DenomsProxy>.plusAssign(values: kotlin.collections.Iterable<ibc.applications.transfer.v1.TokenOuterClass.Denom>) {
      addAll(values)
    }
    /**
     * ```
     * denoms returns all denominations.
     * ```
     *
     * `repeated .ibc.applications.transfer.v1.Denom denoms = 1 [json_name = "denoms", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Denoms"];`
     * @param index The index to set the value at.
     * @param value The denoms to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDenoms")
    public operator fun com.google.protobuf.kotlin.DslList<ibc.applications.transfer.v1.TokenOuterClass.Denom, DenomsProxy>.set(index: kotlin.Int, value: ibc.applications.transfer.v1.TokenOuterClass.Denom) {
      _builder.setDenoms(index, value)
    }
    /**
     * ```
     * denoms returns all denominations.
     * ```
     *
     * `repeated .ibc.applications.transfer.v1.Denom denoms = 1 [json_name = "denoms", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Denoms"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDenoms")
    public fun com.google.protobuf.kotlin.DslList<ibc.applications.transfer.v1.TokenOuterClass.Denom, DenomsProxy>.clear() {
      _builder.clearDenoms()
    }


    /**
     * ```
     * pagination defines the pagination in the response.
     * ```
     *
     * `.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];`
     */
    public var pagination: cosmos.base.query.v1beta1.Pagination.PageResponse
      @JvmName("getPagination")
      get() = _builder.pagination
      @JvmName("setPagination")
      set(value) {
        _builder.pagination = value
      }
    /**
     * ```
     * pagination defines the pagination in the response.
     * ```
     *
     * `.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];`
     */
    public fun clearPagination() {
      _builder.clearPagination()
    }
    /**
     * ```
     * pagination defines the pagination in the response.
     * ```
     *
     * `.cosmos.base.query.v1beta1.PageResponse pagination = 2 [json_name = "pagination"];`
     * @return Whether the pagination field is set.
     */
    public fun hasPagination(): kotlin.Boolean {
      return _builder.hasPagination()
    }

    public val QueryDenomsResponseKt.Dsl.paginationOrNull: cosmos.base.query.v1beta1.Pagination.PageResponse?
      get() = _builder.paginationOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponse.copy(block: `ibc.applications.transfer.v1`.QueryDenomsResponseKt.Dsl.() -> kotlin.Unit): ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponse =
  `ibc.applications.transfer.v1`.QueryDenomsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ibc.applications.transfer.v1.QueryOuterClass.QueryDenomsResponseOrBuilder.paginationOrNull: cosmos.base.query.v1beta1.Pagination.PageResponse?
  get() = if (hasPagination()) getPagination() else null

