<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/slashing/module/v1/module.proto

namespace GPBMetadata\Cosmos\Slashing\Module\V1;

class Module
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Cosmos\App\V1Alpha1\Module::initOnce();
        $pool->internalAddGeneratedFile(
            '
¤
&cosmos/slashing/module/v1/module.protocosmos.slashing.module.v1"W
Module
	authority (	R	authority:/ºÀ–Ú)
\'github.com/cosmos/cosmos-sdk/x/slashingbproto3'
        , true);

        static::$is_initialized = true;
    }
}

